In [1]:
import pandas as pd
import model.processing_utils as pu
import numpy as np

In [2]:

def parse_categories(filename):
    categories = {}
    current_path = []
    
    with open(filename, 'r', encoding='utf-8') as f:
        lines = f.readlines()
        
    for line in lines:
        if not line.strip() or 'Category ID' in line:
            continue
            
        parts = line.strip().split('\t')
        if len(parts) != 3:
            continue
            
        id, name, path = parts
        levels = path.split(' > ')
        
        # Reset or build current path based on levels
        if len(levels) == 1:
            current_path = []
        current_path = current_path[:len(levels)-1]
        current_path.append(name)
        
        # Build nested dictionary structure
        current_dict = categories
        for i, level in enumerate(levels[:-1]):
            if level not in current_dict:
                current_dict[level] = {"id": "", "subcategories": {}}
            current_dict = current_dict[level]["subcategories"]
            
        # Add the final category
        if levels[-1] not in current_dict:
            current_dict[levels[-1]] = {"id": id}
            if len(current_path) < len(levels):
                current_dict[levels[-1]]["subcategories"] = {}
    
    return categories

In [3]:
import json
file_path = 'data/raw/tax.txt'
category_dict = {}

# Open the file and process it
with open(file_path, "r") as file:
    # Skip the header line
    header = next(file)
    
    for line in file:
        # Split the line into components
        components = line.strip().split("\t")
        
        # Ensure the line has exactly 3 columns
        if len(components) == 3:
            category_id, category_name, category_label = components
            # Split the Category Label into hierarchy levels
            hierarchy = category_label.split(" > ")
            # Add to the dictionary
            category_dict[category_id] = hierarchy

In [4]:
category_dict

{'Category ID': ['Category Label'],
 '4d4b7104d754a06370d81259': ['Arts and Entertainment'],
 '4bf58dd8d48988d182941735': ['Arts and Entertainment', 'Amusement Park'],
 '5109983191d435c0d71c2bb1': ['Arts and Entertainment',
  'Amusement Park',
  'Attraction'],
 '4fceea171983d5d06c3e9823': ['Arts and Entertainment', 'Aquarium'],
 '4bf58dd8d48988d1e1931735': ['Arts and Entertainment', 'Arcade'],
 '4bf58dd8d48988d1e2931735': ['Arts and Entertainment', 'Art Gallery'],
 '63be6904847c3692a84b9b20': ['Arts and Entertainment', 'Bingo Center'],
 '4bf58dd8d48988d1e4931735': ['Arts and Entertainment', 'Bowling Alley'],
 '63be6904847c3692a84b9b21': ['Arts and Entertainment', 'Carnival'],
 '4bf58dd8d48988d17c941735': ['Arts and Entertainment', 'Casino'],
 '52e81612bcbc57f1066b79e7': ['Arts and Entertainment', 'Circus'],
 '4bf58dd8d48988d18e941735': ['Arts and Entertainment', 'Comedy Club'],
 '63be6904847c3692a84b9b22': ['Arts and Entertainment', 'Country Club'],
 '52e81612bcbc57f1066b79ef': ['Arts and Entertainment', 'Country Dance Club'],
 '63be6904847c3692a84b9b23': ['Arts and Entertainment', 'Dance Hall'],
 '52e81612bcbc57f1066b79e8': ['Arts and Entertainment', 'Disc Golf'],
 '63be6904847c3692a84b9c03': ['Arts and Entertainment', 'Disc Golf Course'],
 '5f2c2834b6d05514c704451e': ['Arts and Entertainment', 'Escape Room'],
 '56aa371be4b08b9a8d573532': ['Arts and Entertainment', 'Exhibit'],
 '4eb1daf44b900d56c88a4600': ['Arts and Entertainment', 'Fair'],
 '4bf58dd8d48988d18d941735': ['Arts and Entertainment', 'Gaming Cafe'],
 '4bf58dd8d48988d1f1931735': ['Arts and Entertainment',
  'General Entertainment'],
 '52e81612bcbc57f1066b79ea': ['Arts and Entertainment', 'Go Kart Track'],
 '4bf58dd8d48988d1f0941735': ['Arts and Entertainment', 'Internet Cafe'],
 '5744ccdfe4b0c0459246b4bb': ['Arts and Entertainment', 'Karaoke Box'],
 '52e81612bcbc57f1066b79e6': ['Arts and Entertainment', 'Laser Tag Center'],
 '52e81612bcbc57f1066b79eb': ['Arts and Entertainment', 'Mini Golf Course'],
 '4bf58dd8d48988d17f941735': ['Arts and Entertainment', 'Movie Theater'],
 '56aa371be4b08b9a8d5734de': ['Arts and Entertainment',
  'Movie Theater',
  'Drive-in Theater'],
 '4bf58dd8d48988d17e941735': ['Arts and Entertainment',
  'Movie Theater',
  'Indie Movie Theater'],
 '4bf58dd8d48988d180941735': ['Arts and Entertainment',
  'Movie Theater',
  'Multiplex'],
 '4bf58dd8d48988d181941735': ['Arts and Entertainment', 'Museum'],
 '4bf58dd8d48988d18f941735': ['Arts and Entertainment',
  'Museum',
  'Art Museum'],
 '559acbe0498e472f1a53fa23': ['Arts and Entertainment',
  'Museum',
  'Erotic Museum'],
 '4bf58dd8d48988d190941735': ['Arts and Entertainment',
  'Museum',
  'History Museum'],
 '4bf58dd8d48988d191941735': ['Arts and Entertainment',
  'Museum',
  'Science Museum'],
 '4bf58dd8d48988d11f941735': ['Arts and Entertainment', 'Night Club'],
 '5744ccdfe4b0c0459246b4b8': ['Arts and Entertainment', 'Pachinko Parlor'],
 '63be6904847c3692a84b9b24': ['Arts and Entertainment', 'Party Center'],
 '4bf58dd8d48988d1f2931735': ['Arts and Entertainment',
  'Performing Arts Venue'],
 '56aa371be4b08b9a8d5734db': ['Arts and Entertainment',
  'Performing Arts Venue',
  'Amphitheater'],
 '5032792091d4c4b30a586d5c': ['Arts and Entertainment',
  'Performing Arts Venue',
  'Concert Hall'],
 '4bf58dd8d48988d135941735': ['Arts and Entertainment',
  'Performing Arts Venue',
  'Indie Theater'],
 '4bf58dd8d48988d1e5931735': ['Arts and Entertainment',
  'Performing Arts Venue',
  'Music Venue'],
 '4bf58dd8d48988d1e7931735': ['Arts and Entertainment',
  'Performing Arts Venue',
  'Music Venue',
  'Jazz and Blues Venue'],
 '4bf58dd8d48988d1e9931735': ['Arts and Entertainment',
  'Performing Arts Venue',
  'Music Venue',
  'Rock Club'],
 '4bf58dd8d48988d136941735': ['Arts and Entertainment',
  'Performing Arts Venue',
  'Opera House'],
 '4bf58dd8d48988d137941735': ['Arts and Entertainment',
  'Performing Arts Venue',
  'Theater'],
 '4bf58dd8d48988d192941735': ['Arts and Entertainment', 'Planetarium'],
 '4bf58dd8d48988d1e3931735': ['Arts and Entertainment', 'Pool Hall'],
 '52f2ab2ebcbc57f1066b8b43': ['Arts and Entertainment',
  'Psychic and Astrologer'],
 '507c8c4091d498d9fc8c67a9': ['Arts and Entertainment', 'Public Art'],
 '52e81612bcbc57f1066b79ed': ['Arts and Entertainment',
  'Public Art',
  'Outdoor Sculpture'],
 '52e81612bcbc57f1066b79ee': ['Arts and Entertainment',
  'Public Art',
  'Street Art'],
 '52e81612bcbc57f1066b79e9': ['Arts and Entertainment', 'Roller Rink'],
 '52e81612bcbc57f1066b79ec': ['Arts and Entertainment', 'Salsa Club'],
 '56aa371be4b08b9a8d5734f9': ['Arts and Entertainment', 'Samba School'],
 '4bf58dd8d48988d184941735': ['Arts and Entertainment', 'Stadium'],
 '4bf58dd8d48988d18c941735': ['Arts and Entertainment',
  'Stadium',
  'Baseball Stadium'],
 '4bf58dd8d48988d18b941735': ['Arts and Entertainment',
  'Stadium',
  'Basketball Stadium'],
 '4bf58dd8d48988d189941735': ['Arts and Entertainment',
  'Stadium',
  'Football Stadium'],
 '4bf58dd8d48988d185941735': ['Arts and Entertainment',
  'Stadium',
  'Hockey Stadium'],
 '56aa371be4b08b9a8d573556': ['Arts and Entertainment',
  'Stadium',
  'Rugby Stadium'],
 '4bf58dd8d48988d188941735': ['Arts and Entertainment',
  'Stadium',
  'Soccer Stadium'],
 '4e39a891bd410d7aed40cbc2': ['Arts and Entertainment',
  'Stadium',
  'Tennis Stadium'],
 '4bf58dd8d48988d187941735': ['Arts and Entertainment',
  'Stadium',
  'Track Stadium'],
 '4bf58dd8d48988d1d6941735': ['Arts and Entertainment', 'Strip Club'],
 '63be6904847c3692a84b9b25': ['Arts and Entertainment', 'Ticket Seller'],
 '5f2c14a5b6d05514c7042eb7': ['Arts and Entertainment', 'VR Cafe'],
 '4bf58dd8d48988d193941735': ['Arts and Entertainment', 'Water Park'],
 '4bf58dd8d48988d17b941735': ['Arts and Entertainment', 'Zoo'],
 '58daa1558bbb0b01f18ec1fd': ['Arts and Entertainment', 'Zoo', 'Zoo Exhibit'],
 '4d4b7105d754a06375d81259': ['Business and Professional Services'],
 '52e81612bcbc57f1066b7a3d': ['Business and Professional Services',
  'Advertising Agency'],
 '63be6904847c3692a84b9b26': ['Business and Professional Services',
  'Agriculture and Forestry Service'],
 '63be6904847c3692a84b9b27': ['Business and Professional Services',
  'Appraiser'],
 '5fac002599ce226e27fe72e5': ['Business and Professional Services',
  'Architecture Firm'],
 '63be6904847c3692a84b9b28': ['Business and Professional Services',
  'Art Restoration Service'],
 '58daa1558bbb0b01f18ec1d6': ['Business and Professional Services',
  'Art Studio'],
 '63be6904847c3692a84b9b29': ['Business and Professional Services',
  'Audiovisual Service'],
 '4bf58dd8d48988d173941735': ['Business and Professional Services',
  'Auditorium'],
 '63be6904847c3692a84b9b2a': ['Business and Professional Services',
  'Automation and Control System'],
 '63be6904847c3692a84b9b2b': ['Business and Professional Services',
  'Automotive Service'],
 '52f2ab2ebcbc57f1066b8b44': ['Business and Professional Services',
  'Automotive Service',
  'Automotive Repair Shop'],
 '4f04ae1f2fb6e1c99f3db0ba': ['Business and Professional Services',
  'Automotive Service',
  'Car Wash and Detail'],
 '63be6904847c3692a84b9b2c': ['Business and Professional Services',
  'Automotive Service',
  'Motorcycle Repair Shop'],
 '63be6904847c3692a84b9b2d': ['Business and Professional Services',
  'Automotive Service',
  'Oil Change Service'],
 '63be6904847c3692a84b9b2e': ['Business and Professional Services',
  'Automotive Service',
  'Smog Check Shop'],
 '63be6904847c3692a84b9b2f': ['Business and Professional Services',
  'Automotive Service',
  'Tire Repair Shop'],
 '63be6904847c3692a84b9b30': ['Business and Professional Services',
  'Automotive Service',
  'Towing Service'],
 '63be6904847c3692a84b9b31': ['Business and Professional Services',
  'Automotive Service',
  'Transmissions Shop'],
 '5f2c1e0db6d05514c70436d4': ['Business and Professional Services',
  'Automotive Service',
  'Vehicle Inspection Station'],
 '56aa371be4b08b9a8d5734cf': ['Business and Professional Services',
  'Ballroom'],
 '56aa371be4b08b9a8d573517': ['Business and Professional Services',
  'Business Center'],
 '5453de49498eade8af355881': ['Business and Professional Services',
  'Business Service'],
 '63be6904847c3692a84b9b33': ['Business and Professional Services',
  'Career Counselor'],
 '63be6904847c3692a84b9b34': ['Business and Professional Services',
  'Chemicals and Gasses Manufacturer'],
 '5744ccdfe4b0c0459246b4c7': ['Business and Professional Services',
  'Child Care Service'],
 '4f4532974b9074f6e4fb0104': ['Business and Professional Services',
  'Child Care Service',
  'Daycare'],
 '63be6904847c3692a84b9b35': ['Business and Professional Services',
  'Computer Repair Service'],
 '63be6904847c3692a84b9b36': ['Business and Professional Services',
  'Construction'],
 '4bf58dd8d48988d1ff931735': ['Business and Professional Services',
  'Convention Center'],
 '4bf58dd8d48988d100941735': ['Business and Professional Services',
  'Convention Center',
  'Conference Room'],
 '63be6904847c3692a84b9b37': ['Business and Professional Services',
  'Creative Service'],
 '4bf58dd8d48988d1f4941735': ['Business and Professional Services',
  'Design Studio'],
 '63be6904847c3692a84b9b38': ['Business and Professional Services',
  'Direct Mail and Email Marketing Service'],
 '52e81612bcbc57f1066b7a37': ['Business and Professional Services',
  'Distribution Center'],
 '63be6904847c3692a84b9b39': ['Business and Professional Services',
  'Electrical Equipment Supplier'],
 '52f2ab2ebcbc57f1066b8b57': ['Business and Professional Services',
  'Employment Agency'],
 '63be6904847c3692a84b9b3a': ['Business and Professional Services',
  'Engineer'],
 '63be6904847c3692a84b9b3b': ['Business and Professional Services',
  'Entertainment Agency'],
 '56aa371be4b08b9a8d573554': ['Business and Professional Services',
  'Entertainment Service'],
 '63be6904847c3692a84b9b3c': ['Business and Professional Services',
  'Equipment Rental Service'],
 '5454152e498ef71e2b9132c6': ['Business and Professional Services',
  'Event Service'],
 '4bf58dd8d48988d171941735': ['Business and Professional Services',
  'Event Space'],
 '4eb1bea83b7b6f98df247e06': ['Business and Professional Services', 'Factory'],
 '56aa371be4b08b9a8d573523': ['Business and Professional Services',
  'Film Studio'],
 '63be6904847c3692a84b9b3d': ['Business and Professional Services',
  'Financial Service'],
 '63be6904847c3692a84b9b3e': ['Business and Professional Services',
  'Financial Service',
  'Accounting and Bookkeeping Service'],
 '63be6904847c3692a84b9b3f': ['Business and Professional Services',
  'Financial Service',
  'Banking and Finance'],
 '52f2ab2ebcbc57f1066b8b56': ['Business and Professional Services',
  'Financial Service',
  'Banking and Finance',
  'ATM'],
 '4bf58dd8d48988d10a951735': ['Business and Professional Services',
  'Financial Service',
  'Banking and Finance',
  'Bank'],
 '5032850891d4c4b30a586d62': ['Business and Professional Services',
  'Financial Service',
  'Banking and Finance',
  'Credit Union'],
 '63be6904847c3692a84b9b40': ['Business and Professional Services',
  'Financial Service',
  'Business Broker'],
 '52f2ab2ebcbc57f1066b8b2d': ['Business and Professional Services',
  'Financial Service',
  'Check Cashing Service'],
 '63be6904847c3692a84b9b41': ['Business and Professional Services',
  'Financial Service',
  'Collections Service'],
 '63be6904847c3692a84b9b42': ['Business and Professional Services',
  'Financial Service',
  'Credit Counseling and Bankruptcy Service'],
 '5744ccdfe4b0c0459246b4be': ['Business and Professional Services',
  'Financial Service',
  'Currency Exchange'],
 '63be6904847c3692a84b9b43': ['Business and Professional Services',
  'Financial Service',
  'Financial Planner'],
 '63be6904847c3692a84b9b44': ['Business and Professional Services',
  'Financial Service',
  'Loans Agency'],
 '63be6904847c3692a84b9b45': ['Business and Professional Services',
  'Financial Service',
  'Stock Broker'],
 '56aa371be4b08b9a8d573550': ['Business and Professional Services',
  'Food and Beverage Service'],
 '63be6904847c3692a84b9b46': ['Business and Professional Services',
  'Food and Beverage Service',
  'Caterer'],
 '63be6904847c3692a84b9b47': ['Business and Professional Services',
  'Food and Beverage Service',
  'Food Distribution Center'],
 '4f4534884b9074f6e4fb0174': ['Business and Professional Services',
  'Funeral Home'],
 '63be6904847c3692a84b9b48': ['Business and Professional Services',
  'Geological Service'],
 '54541900498ea6ccd0202697': ['Business and Professional Services',
  'Health and Beauty Service'],
 '63be6904847c3692a84b9b49': ['Business and Professional Services',
  'Health and Beauty Service',
  'Barbershop'],
 '52e81612bcbc57f1066b7a27': ['Business and Professional Services',
  'Health and Beauty Service',
  'Bath House'],
 '52f2ab2ebcbc57f1066b8b20': ['Business and Professional Services',
  'Health and Beauty Service',
  'Body Piercing Shop'],
 '52f2ab2ebcbc57f1066b8b1d': ['Business and Professional Services',
  'Health and Beauty Service',
  'Dry Cleaner'],
 '63be6904847c3692a84b9b4a': ['Business and Professional Services',
  'Health and Beauty Service',
  'Hair Removal Service'],
 '4bf58dd8d48988d110951735': ['Business and Professional Services',
  'Health and Beauty Service',
  'Hair Salon'],
 '52f2ab2ebcbc57f1066b8b3c': ['Business and Professional Services',
  'Health and Beauty Service',
  'Massage Clinic'],
 '4f04aa0c2fb6e1c99f3db0b8': ['Business and Professional Services',
  'Health and Beauty Service',
  'Nail Salon'],
 '63be6904847c3692a84b9b4b': ['Business and Professional Services',
  'Health and Beauty Service',
  'Skin Care Clinic'],
 '4bf58dd8d48988d1ed941735': ['Business and Professional Services',
  'Health and Beauty Service',
  'Spa'],
 '4d1cf8421a97d635ce361c31': ['Business and Professional Services',
  'Health and Beauty Service',
  'Tanning Salon'],
 '4bf58dd8d48988d1de931735': ['Business and Professional Services',
  'Health and Beauty Service',
  'Tattoo Parlor'],
 '63be6904847c3692a84b9b58': ['Business and Professional Services',
  'Home Improvement Service'],
 '63be6904847c3692a84b9b4c': ['Business and Professional Services',
  'Home Improvement Service',
  'Bathroom Contractor'],
 '63be6904847c3692a84b9b4d': ['Business and Professional Services',
  'Home Improvement Service',
  'Carpenter'],
 '63be6904847c3692a84b9b4e': ['Business and Professional Services',
  'Home Improvement Service',
  'Carpet and Flooring Contractor'],
 '63be6904847c3692a84b9b4f': ['Business and Professional Services',
  'Home Improvement Service',
  'Chimney Sweep'],
 '63be6904847c3692a84b9b50': ['Business and Professional Services',
  'Home Improvement Service',
  'Deck and Patio Contractor'],
 '63be6904847c3692a84b9b51': ['Business and Professional Services',
  'Home Improvement Service',
  'Doors and Windows Contractor'],
 '63be6904847c3692a84b9b52': ['Business and Professional Services',
  'Home Improvement Service',
  'Electrician'],
 '63be6904847c3692a84b9b53': ['Business and Professional Services',
  'Home Improvement Service',
  'Fence Contractor'],
 '63be6904847c3692a84b9b54': ['Business and Professional Services',
  'Home Improvement Service',
  'Garage Door Supplier'],
 '63be6904847c3692a84b9b55': ['Business and Professional Services',
  'Home Improvement Service',
  'General Contractor'],
 '63be6904847c3692a84b9b56': ['Business and Professional Services',
  'Home Improvement Service',
  'Heating, Ventilating and Air Conditioning Contractor'],
 '63be6904847c3692a84b9b57': ['Business and Professional Services',
  'Home Improvement Service',
  'Home Inspection'],
 '545419b1498ea6ccd0202f58': ['Business and Professional Services',
  'Home Improvement Service',
  'Home Service'],
 '63be6904847c3692a84b9b59': ['Business and Professional Services',
  'Home Improvement Service',
  'Interior Designer'],
 '63be6904847c3692a84b9b5a': ['Business and Professional Services',
  'Home Improvement Service',
  'Kitchen Remodeler'],
 '63be6904847c3692a84b9b5b': ['Business and Professional Services',
  'Home Improvement Service',
  'Landscaper and Gardener'],
 '63be6904847c3692a84b9b5c': ['Business and Professional Services',
  'Home Improvement Service',
  'Mover'],
 '63be6904847c3692a84b9b5d': ['Business and Professional Services',
  'Home Improvement Service',
  'Painter'],
 '63be6904847c3692a84b9b5e': ['Business and Professional Services',
  'Home Improvement Service',
  'Pest Control Service'],
 '63be6904847c3692a84b9b5f': ['Business and Professional Services',
  'Home Improvement Service',
  'Plumber'],
 '63be6904847c3692a84b9b60': ['Business and Professional Services',
  'Home Improvement Service',
  'Professional Cleaning Service'],
 '63be6904847c3692a84b9b61': ['Business and Professional Services',
  'Home Improvement Service',
  'Roofer'],
 '63be6904847c3692a84b9b62': ['Business and Professional Services',
  'Home Improvement Service',
  'Sewer Contractor'],
 '63be6904847c3692a84b9b63': ['Business and Professional Services',
  'Home Improvement Service',
  'Swimming Pool Maintenance and Service'],
 '63be6904847c3692a84b9b64': ['Business and Professional Services',
  'Home Improvement Service',
  'Tree Service'],
 '63be6904847c3692a84b9b65': ['Business and Professional Services',
  'Home Improvement Service',
  'Upholstery Service'],
 '63be6904847c3692a84b9b66': ['Business and Professional Services',
  'Human Resources Agency'],
 '63be6904847c3692a84b9b67': ['Business and Professional Services',
  'Import and Export Service'],
 '63be6904847c3692a84b9b68': ['Business and Professional Services',
  'Industrial Equipment Supplier'],
 '56aa371be4b08b9a8d5734d7': ['Business and Professional Services',
  'Industrial Estate'],
 '58daa1558bbb0b01f18ec1f1': ['Business and Professional Services',
  'Insurance Agency'],
 '63be6904847c3692a84b9b69': ['Business and Professional Services',
  'Laboratory'],
 '52f2ab2ebcbc57f1066b8b33': ['Business and Professional Services',
  'Laundromat'],
 '4bf58dd8d48988d1fc941735': ['Business and Professional Services',
  'Laundry Service'],
 '63be6904847c3692a84b9b6a': ['Business and Professional Services',
  'Leather Supplier'],
 '63be6904847c3692a84b9b6b': ['Business and Professional Services',
  'Legal Service'],
 '63be6904847c3692a84b9b6c': ['Business and Professional Services',
  'Legal Service',
  'Immigration Attorney'],
 '52f2ab2ebcbc57f1066b8b3f': ['Business and Professional Services',
  'Legal Service',
  'Law Office'],
 '5ae95d208a6f17002ce792b2': ['Business and Professional Services',
  'Legal Service',
  'Notary'],
 '52f2ab2ebcbc57f1066b8b1e': ['Business and Professional Services',
  'Locksmith'],
 '63be6904847c3692a84b9b6d': ['Business and Professional Services',
  'Logging Service'],
 '52f2ab2ebcbc57f1066b8b38': ['Business and Professional Services',
  'Lottery Retailer'],
 '63be6904847c3692a84b9b6e': ['Business and Professional Services',
  'Machine Shop'],
 '63be6904847c3692a84b9b6f': ['Business and Professional Services',
  'Management Consultant'],
 '63be6904847c3692a84b9b70': ['Business and Professional Services',
  'Manufacturer'],
 '63be6904847c3692a84b9b71': ['Business and Professional Services',
  'Market Research and Consulting Service'],
 '63be6904847c3692a84b9b72': ['Business and Professional Services',
  'Media Agency'],
 '63be6904847c3692a84b9b73': ['Business and Professional Services',
  'Metals Supplier'],
 '63be6904847c3692a84b9b74': ['Business and Professional Services',
  'Mobile Company'],
 '4bf58dd8d48988d124941735': ['Business and Professional Services', 'Office'],
 '63be6904847c3692a84b9b32': ['Business and Professional Services',
  'Office',
  'Business and Strategy Consulting Office'],
 '5032764e91d4c4b30a586d5a': ['Business and Professional Services',
  'Office',
  'Campaign Office'],
 '5665ef1d498ec706735f0e59': ['Business and Professional Services',
  'Office',
  'Corporate Amenity'],
 '54f4ba06498e2cf5561da814': ['Business and Professional Services',
  'Office',
  'Corporate Cafeteria'],

In [5]:
df_cp = pd.read_csv("data/raw/dataset_TSMC2014_TKY.txt", sep="\t", header=None, encoding='latin1')

df_cp.columns = ["uid", "venue_id", "venue_category_id", "venue_category_name", "lat", "lon", "timezone", "utc_time"]

uid_list = df_cp["uid"].unique().tolist()
print(uid_list)
#shuffle the list using a random seed
np.random.seed(42)
np.random.shuffle(uid_list)
print(uid_list)

df_cp = df_cp[df_cp["uid"].isin(uid_list[:1083])].reset_index(drop=True)
df_cp

[1541, 868, 114, 1458, 1635, 2033, 589, 2290, 471, 886, 265, 159, 1390, 214, 1240, 1842, 96, 1876, 499, 1206, 904, 1143, 1555, 252, 1895, 941, 1056, 1233, 1222, 1906, 1552, 1386, 1317, 2085, 1064, 1349, 1982, 2060, 2243, 847, 1029, 1967, 13, 1964, 9, 1965, 64, 6, 116, 1618, 1324, 1979, 610, 2015, 349, 2287, 1726, 1928, 336, 1379, 775, 972, 931, 1746, 187, 722, 2023, 1808, 135, 1248, 1540, 23, 1907, 680, 1621, 1088, 1790, 1701, 1100, 1961, 1320, 953, 113, 2027, 2054, 863, 476, 1924, 1844, 41, 2022, 3, 2278, 2011, 627, 925, 1132, 390, 1463, 1714, 1384, 917, 423, 1341, 207, 1497, 819, 1638, 1437, 168, 1336, 563, 2059, 1690, 557, 1241, 2000, 841, 29, 1327, 1151, 920, 2121, 1932, 615, 701, 1474, 893, 1611, 1084, 763, 271, 1663, 988, 1676, 833, 300, 1871, 1205, 21, 935, 644, 1216, 1381, 921, 365, 1640, 525, 1412, 1616, 422, 2199, 1466, 1887, 992, 1087, 1481, 81, 1938, 733, 1527, 430, 330, 1937, 161, 285, 425, 831, 822, 1830, 1884, 666, 530, 677, 342, 2250, 1182, 1917, 1557, 2103, 1509, 2073, 1519, 1224, 656, 2046, 547, 1372, 149, 294, 1396, 1996, 1338, 1617, 734, 641, 1303, 806, 1809, 115, 997, 1158, 53, 1699, 1713, 583, 1711, 2198, 1658, 1322, 2212, 2284, 1486, 1883, 1388, 1040, 1646, 845, 1916, 42, 2258, 65, 343, 1002, 1796, 1480, 371, 264, 1693, 2164, 785, 556, 936, 1672, 1795, 1941, 955, 2012, 1960, 212, 426, 482, 1321, 86, 838, 2204, 183, 51, 146, 1761, 1518, 2156, 1826, 504, 1913, 1267, 1323, 1973, 1793, 358, 92, 1903, 1309, 612, 354, 1789, 749, 790, 1765, 1217, 1799, 754, 667, 232, 1922, 729, 409, 655, 653, 2, 1352, 1512, 2187, 1710, 1018, 2083, 1462, 1362, 1667, 593, 2260, 1190, 1587, 1108, 874, 2267, 318, 155, 263, 1147, 1828, 1930, 1007, 1076, 1753, 1807, 1402, 1346, 172, 1332, 284, 2134, 1707, 156, 18, 1471, 59, 191, 929, 1788, 1389, 315, 1387, 1919, 1296, 494, 1031, 324, 1516, 1999, 1428, 782, 1912, 1918, 2167, 1086, 517, 1308, 1745, 697, 1097, 496, 586, 1226, 1041, 951, 632, 1987, 498, 211, 2006, 584, 1989, 1734, 2026, 1454, 900, 439, 823, 329, 1392, 237, 391, 1880, 947, 1784, 75, 1782, 1383, 508, 1545, 737, 1476, 620, 767, 1416, 1265, 1610, 514, 431, 1872, 2218, 996, 624, 2190, 2177, 1161, 1561, 950, 1357, 266, 1550, 849, 27, 1650, 1677, 1089, 928, 1360, 2058, 1210, 1491, 2236, 2092, 575, 1865, 1877, 1861, 778, 177, 1531, 712, 1231, 808, 233, 314, 458, 1735, 2086, 1768, 368, 805, 2234, 1944, 978, 695, 379, 1642, 2286, 1411, 8, 837, 1866, 250, 36, 720, 452, 1528, 160, 1418, 881, 2056, 1350, 1853, 690, 1847, 1600, 454, 1974, 225, 960, 1329, 1607, 1514, 2262, 26, 1505, 1042, 477, 1070, 37, 1027, 1055, 1106, 1529, 1643, 1892, 1783, 1328, 1187, 394, 2145, 1081, 652, 386, 278, 151, 1833, 1284, 1453, 1860, 472, 190, 261, 948, 244, 963, 958, 434, 62, 230, 369, 1800, 1012, 770, 1801, 2112, 435, 693, 550, 192, 299, 1729, 61, 970, 2151, 487, 1931, 456, 725, 63, 507, 280, 2070, 1092, 361, 1096, 55, 741, 87, 519, 1822, 69, 957, 1891, 2043, 1905, 1851, 1013, 1957, 1283, 2037, 1585, 2110, 2150, 2235, 1821, 885, 1325, 1535, 17, 728, 197, 1405, 67, 1066, 219, 492, 1021, 524, 109, 236, 1441, 325, 449, 1648, 392, 418, 1020, 397, 200, 1246, 1772, 2115, 1819, 2087, 1499, 577, 2153, 1304, 727, 2125, 869, 1737, 781, 2211, 465, 804, 502, 682, 2158, 1988, 44, 1537, 700, 2214, 1995, 1678, 699, 1774, 689, 144, 175, 1492, 1740, 503, 1733, 1427, 410, 2020, 1162, 1079, 58, 1578, 839, 1722, 1189, 1743, 1766, 2062, 2077, 444, 461, 322, 1120, 1393, 2259, 1134, 1836, 1062, 1950, 599, 1010, 1301, 779, 138, 2035, 2116, 1060, 650, 721, 2140, 516, 287, 375, 1811, 179, 1251, 619, 2217, 756, 1767, 401, 1123, 357, 60, 549, 1367, 1881, 2273, 1706, 80, 1268, 1738, 2034, 753, 1477, 1560, 1547, 1595, 221, 2274, 1370, 867, 766, 455, 1685, 2109, 663, 459, 830, 1255, 2090, 2163, 1103, 70, 1697, 626, 2179, 40, 1302, 275, 686, 100, 616, 515, 591, 698, 1354, 560, 118, 199, 1400, 1058, 321, 1723, 399, 943, 746, 393, 559, 991, 981, 1581, 1622, 2240, 1468, 1504, 1634, 478, 1608, 827, 784, 703, 2280, 1751, 1893, 105, 1124, 1119, 112, 611, 268, 1445, 1605, 1538, 1464, 432, 2288, 2241, 1168, 848, 2036, 834, 1736, 148, 1856, 757, 932, 2154, 189, 2282, 640, 889, 54, 253, 851, 544, 1074, 2127, 1033, 538, 752, 1223, 1343, 587, 1377, 173, 1962, 1368, 1798, 1340, 363, 2039, 141, 1815, 1647, 346, 171, 467, 1330, 1970, 1127, 1792, 1954, 2275, 2030, 1493, 1823, 2031, 1573, 1703, 807, 142, 1873, 526, 1192, 1047, 272, 1318, 1220, 1564, 119, 1869, 2174, 316, 710, 1429, 1026, 891, 1156, 675, 812, 227, 339, 1008, 427, 1045, 1264, 2028, 1580, 201, 311, 176, 704, 91, 1812, 136, 965, 2184, 2254, 707, 2041, 1673, 2044, 493, 307, 485, 743, 481, 1333, 1942, 1299, 2257, 326, 229, 1590, 1035, 56, 1517, 1104, 789, 919, 1260, 1152, 543, 908, 1945, 1244, 2129, 1875, 1582, 2018, 820, 777, 128, 1082, 364, 609, 14, 1968, 1565, 2252, 1940, 95, 961, 1925, 429, 2263, 1763, 279, 443, 882, 895, 1983, 910, 242, 2186, 123, 133, 669, 795, 934, 576, 267, 773, 99, 842, 1837, 600, 25, 1503, 303, 1004, 1629, 939, 1142, 1195, 2068, 1098, 534, 249, 761, 254, 1679, 1410, 824, 1805, 1952, 1948, 715, 977, 645, 1530, 104, 578, 2189, 1395, 1813, 1335, 1543, 1050, 1963, 446, 909, 500, 218, 417, 2224, 2247, 974, 621, 1855, 1908, 579, 750, 1036, 864, 1461, 685, 309, 1939, 412, 857, 406, 888, 1665, 497, 1958, 1933, 82, 1117, 1671, 1739, 2100, 181, 238, 2042, 90, 1681, 553, 2197, 571, 2207, 875, 1689, 347, 2120, 511, 1794, 52, 2128, 2239, 643, 1953, 11, 241, 832, 736, 1450, 1398, 1771, 739, 1532, 93, 635, 1742, 1980, 403, 1628, 1879, 1687, 1180, 2161, 127, 2021, 1542, 1016, 1154, 618, 1623, 1575, 2270, 1290, 1273, 1951, 1604, 20, 1921, 1894, 130, 1839, 1802, 2226, 1899, 1613, 1135, 1242, 319, 1166, 276, 2230, 210, 1544, 1633, 94, 1054, 490, 1188, 1254, 1399, 1534, 860, 1051, 702, 628, 595, 540, 1653, 2173, 1846, 603, 1885, 1659, 1116, 1593, 1770, 1498, 1243, 1214, 1228, 1001, 651, 1239, 157, 1845, 184, 2292, 327, 937, 1067, 892, 464, 420, 713, 1434, 2101, 306, 1946, 1452, 774, 486, 372, 143, 1358, 788, 670, 1978, 351, 337, 362, 1374, 2049, 1285, 1549, 378, 1708, 688, 2067, 2130, 259, 174, 1175, 1298, 50, 1599, 1160, 247, 987, 1069, 2072, 374, 1510, 2082, 48, 182, 1803, 523, 270, 717, 1090, 1603, 1068, 1878, 15, 1720, 505, 982, 215, 292, 1490, 836, 574, 1110, 366, 922, 1909, 1888, 376, 1563, 2093, 613, 884, 2061, 844, 942, 637, 1760, 333, 835, 111, 2271, 1849, 1553, 320, 1034, 415, 2245, 1128, 569, 568, 879, 771, 520, 97, 1586, 596, 1121, 120, 2238, 1716, 470, 1451, 1949, 413, 282, 968, 545, 377, 147, 1652, 1501, 1485, 532, 606, 1508, 966, 194, 1889, 1046, 1998, 1896, 1366, 2108, 708, 38, 2019, 2268, 2233, 2213, 1754, 186, 901, 2272, 1136, 1112, 4, 998, 1417, 1234, 1867, 1380, 2171, 2017, 975, 811, 2069, 1959, 389, 1150, 692, 2005, 566, 1339, 2094, 861, 2182, 367, 1063, 1364, 1597, 709, 83, 355, 1133, 474, 495, 1882, 2137, 1758, 1923, 1085, 1286, 209, 442, 245, 1572, 1728, 1574, 1157, 1289, 1421, 760, 1926, 980, 1741, 664, 1955, 985, 1334, 2057, 1779, 150, 2008, 1030, 1275, 1862, 590, 2170, 295, 1111, 1969, 602, 2123, 1691, 1715, 730, 217, 1632, 755, 164, 954, 1369, 976, 1061, 2231, 101, 555, 2079, 1470, 122, 341, 912, 1153, 654, 228, 2144, 7, 335, 49, 1755, 1449, 117, 2004, 216, 1348, 906, 1546, 140, 801, 469, 283, 2099, 491, 288, 1776, 1000, 220, 286, 387, 759, 1196, 139, 1936, 810, 1281, 1890, 76, 2155, 1247, 255, 2281, 1478, 305, 239, 565, 2010, 1219, 2007, 1523, 1279, 762, 518, 2264, 68, 235, 1375, 1314, 2176, 1859, 262, 672, 2216, 78, 724, 1692, 780, 1204, 1044, 913, 1288, 340, 39, 1295, 2114, 1, 1854, 956, 751, 1006, 1904, 398, 2055, 1834, 594, 1835, 1718, 995, 1864, 548, 414, 2016, 1446, 1165, 2080, 2209, 353, 1897, 1025, 1570, 1456, 360, 1139, 898, 1985, 521, 1091, 257, 887, 204, 1171, 258, 1624, 787, 622, 1408, 1502, 1744, 2228, 927, 679, 1250, 1975, 121, 1115, 2242, 370, 2227, 813, 552, 2169, 786, 1163, 88, 1065, 296, 899, 573, 1075, 607, 134, 1159, 1270, 905, 445, 1797, 1748, 798, 1174, 2143, 1756, 2111, 2160, 334, 1971, 1101, 2146, 986, 460, 46, 2220, 274, 1539, 484, 1886, 802, 684, 828, 1651, 2200, 208, 1786, 73, 1356, 2149, 1832, 1977, 2210, 256, 673, 2147, 222, 2168, 1460, 1594, 297, 558, 1028, 1515, 312, 1596, 962, 2165, 944, 598, 1211, 2180, 1413, 2201, 382, 2126, 1419, 441, 404, 1915, 2071, 855, 154, 1005, 732, 2089, 897, 12, 1347, 77, 1107, 818, 748, 2246, 110, 2203, 1080, 1293, 758, 1191, 195, 107, 1759, 2206, 79, 1077, 1696, 289, 33, 633, 2048, 373, 1620, 1730, 129, 1791, 2052, 1725, 2024, 2131, 592, 747, 1993, 1868, 711, 479, 564, 2142, 533, 914, 1465, 938, 945, 1297, 1422, 1176, 1155, 489, 1700, 629, 1245, 1680, 623, 1526, 1420, 313, 1814, 1731, 163, 1049, 1207, 1209, 854, 1661, 1237, 1577, 529, 1695, 1212, 381, 772, 657, 1606, 2229, 411, 796, 605, 66, 1199, 400, 1238, 405, 1083, 344, 2066, 1752, 1407, 880, 878, 350, 735, 1569, 902, 1997, 1626, 1257, 1184, 1487, 522, 1525, 668, 1705, 1113, 1655, 1253, 1179, 102, 723, 2138, 421, 510, 383, 1670, 1271, 2266, 1576, 1137, 1636, 896, 1011, 178, 437, 814, 1406, 993, 1614, 1986, 2032, 1698, 1291, 719, 866, 1203, 1558, 588, 162, 1831, 2215, 952, 185, 1947, 395, 1920, 1105, 2221, 1827, 24, 1202, 1615, 1435, 546, 1929, 1683, 2119, 1507, 98, 817, 424, 764, 671, 2040, 1342, 16, 608, 71, 843, 783, 1443, 1378, 1627, 396, 2285, 428, 251, 2096, 2098, 463, 2289, 1778, 2276, 388, 1625, 513, 1459, 1141, 1870, 858, 1017, 131, 1994, 1287, 1014, 206, 2196, 731, 946, 106, 196, 969, 2064, 2208, 1307, 797, 1682, 528, 1602, 457, 416, 1319, 1122, 1562, 2078, 170, 31, 2255, 1639, 1032, 203, 2225, 660, 537, 2279, 2122, 1900, 2074, 213, 291, 816, 791, 2014, 466, 1359, 28, 648, 740, 43, 248, 85, 1430, 631, 2076, 1071, 580, 794, 2291, 462, 2166, 1780, 1898, 636, 1601, 408, 646, 1806, 1992, 1274, 933, 2251, 1310, 2133, 345, 1956, 2193, 1694, 964, 1684, 883, 2095, 1598, 2202, 352, 949, 1824, 246, 1775, 1305, 290, 862, 1785, 2053, 125, 1292, 1019, 1126, 438, 1225, 1702, 1312, 1177, 1848, 501, 277, 915, 2195, 1448, 1943, 1424, 273, 2009, 1315, 2084, 1810, 1023, 2117, 1258, 1816, 829, 1439, 647, 1631, 1394, 1556, 22, 1256, 2107, 572, 304, 1363, 582, 2261, 911, 1592, 1227, 30, 1972, 1927, 2001, 1674, 2188, 1455, 716, 2181, 473, 859, 1440, 2159, 1095, 1910, 567, 1522, 1263, 1984, 800, 2002, 1762, 1109, 1496, 1057, 1668, 1125, 1781, 1282, 2223, 1178, 2249, 551, 1583, 923, 2113, 359, 2248, 281, 1817, 512, 744, 541, 1130, 506, 1294, 310, 1230, 597, 205, 167, 193, 2102, 973, 338, 1208, 821, 451, 1432, 2139, 2148, 2118, 1630, 2104, 2091, 224, 1249, 967, 1818, 2135, 792, 2081, 865, 1467, 1278, 718, 152, 448, 1567, 1447, 328, 1073, 691, 1118, 1749, 542, 240, 103, 1521, 1840, 475, 1773, 1266, 768, 32, 480, 380, 2244, 1787, 2232, 2269, 681, 1024, 2205, 570, 1371, 1269, 1436, 1022, 1039, 1131, 2265, 84, 1331, 1280, 407, 1185, 2051, 1015, 166, 2124, 726, 436, 990, 2162, 1675, 323, 1641, 815, 234, 1901, 2141, 1144, 940, 1666, 1099, 638, 994, 402, 2152, 450, 2194, 890, 1579, 642, 1236, 1588, 1554, 1183, 1511, 298, 1072, 453, 1401, 1645, 662, 793, 1619, 1102, 1609, 1551, 674, 877, 1169, 1145, 2029, 856, 1361, 293, 1403, 661, 2132, 2219, 1444, 1850, 1426, 776, 169, 971, 2157, 5, 687, 89, 1757, 269, 989, 1475, 47, 1252, 384, 317, 1433, 2237, 2106, 1548, 1469, 852, 1149, 1200, 1164, 10, 870, 1093, 1213, 1415, 1482, 1649, 108, 1003, 132, 180, 1457, 35, 1747, 1259, 1934, 1316, 198, 1902, 614, 34, 1404, 658, 1235, 665, 871, 419, 1911, 2256, 45, 440, 2050, 1306, 1874, 2013, 153, 983, 1172, 447, 531, 356, 1489, 554, 706, 930, 1337, 74, 2293, 1473, 1584, 1863, 850, 1221, 1197, 1657, 1397, 1559, 659, 1536, 1272, 1717, 2283, 1201, 1841, 769, 1656, 625, 585, 1727, 1218, 1148, 683, 705, 243, 676, 1644, 1472, 903, 1858, 1484, 1442, 1506, 1852, 302, 1261, 617, 1764, 126, 799, 1513, 1669, 1637, 745, 1425, 1664, 332, 1382, 483, 72, 2192, 124, 872, 1059, 694, 1198, 1591, 1483, 1589, 1732, 1524, 1138, 1078, 1660, 1520, 979, 1229, 226, 1719, 1533, 539, 2088, 840, 1981, 19, 1820, 826, 581, 488, 468, 1365, 2105, 223, 1495, 348, 1353, 2222, 1300, 1376, 604, 308, 1052, 385, 1114, 1186, 1431, 2136, 2191, 742, 1146, 1704, 1344, 1391, 433, 1654, 1976, 1276, 1712, 1194, 1326, 1688, 1479, 145, 1094, 2003, 601, 260, 1373, 924, 1686, 1857, 1494, 1777, 1173, 1129, 536, 1053, 1935, 1750, 678, 630, 1990, 1662, 2175, 1313, 1709, 1009, 562, 165, 1825, 1721, 1037, 1438, 1843, 809, 1277, 2097, 2183, 696, 1181, 1311, 1914, 1838, 2253, 1500, 2025, 2047, 1140, 1043, 1385, 1351, 894, 231, 2185, 561, 1038, 527, 1170, 926, 1215, 738, 1566, 876, 137, 907, 2065, 1345, 1048, 509, 2038, 765, 803, 1612, 1769, 1423, 916, 331, 535, 1167, 2075, 1966, 1193, 1355, 2178, 825, 2045, 918, 714, 1568, 1414, 1571, 984, 649, 1804, 1488, 999, 202, 1724, 639, 1991, 853, 2063, 873, 2277, 959, 301, 634, 1262, 1829, 846, 188, 158, 1232, 57, 2172, 1409]

,uid,venue_id,venue_category_id,venue_category_name,lat,lon,timezone,utc_time
0,114,4c16fdda96040f477cc473a5,4d954b0ea243a5684a65b473,Convenience Store,35.714542,139.480065,540,Tue Apr 03 19:12:07 +0000 2012
1,114,4b3eae5cf964a520b4a025e3,4bf58dd8d48988d129951735,Train Station,35.700253,139.480255,540,Tue Apr 03 19:35:36 +0000 2012
2,589,4b5ed39cf964a520079a29e3,4bf58dd8d48988d1eb931735,Airport,35.548963,139.784611,540,Tue Apr 03 19:59:06 +0000 2012
3,589,4e014c11c65b896d116d480c,4bf58dd8d48988d1fe931735,Bus Station,35.575028,139.758786,540,Tue Apr 03 20:01:54 +0000 2012
4,471,4ba88a28f964a52028df39e3,4bf58dd8d48988d1d1941735,Ramen / Noodle House,35.709190,139.773822,540,Tue Apr 03 20:09:35 +0000 2012
...,...,...,...,...,...,...,...,...
273498,2200,4b0587a6f964a5203d9e22e3,4bf58dd8d48988d129951735,Train Station,35.690803,139.700279,540,Sat Feb 16 02:32:51 +0000 2013
273499,2277,4b82669cf964a5209ed130e3,4bf58dd8d48988d172941735,Post Office,35.710080,139.790999,540,Sat Feb 16 02:33:48 +0000 2013
273500,2277,4b56c4c5f964a520c41a28e3,4bf58dd8d48988d1fd931735,Subway,35.709845,139.790801,540,Sat Feb 16 02:34:32 +0000 2013
273501,326,4bab3456f964a5204d993ae3,4bf58dd8d48988d1e9931735,Music Venue,35.656939,139.702518,540,Sat Feb 16 02:34:35 +0000 2013
273502,1050,4b5a7486f964a52027c628e3,4bf58dd8d48988d10d951735,Record Shop,35.704069,139.579496,540,Sat Feb 16 02:35:29 +0000 2013

In [ ]:
df_cp.dropna(subset=["venue_category_id", "timezone"], inplace=True)
#rename lon to lng and venue_id to venueID
df_cp.rename(columns={"lon": "lng", "venue_id": "venueID", 'utc_time':'time', 'venue_category_name':'venue_descr'}, inplace=True)
#reorder columns
df_cp = df_cp[['uid',  'lat', 'lng', 'venueID', 'venue_descr', 'time', 'venue_category_id']]

df_cp["venueID"] = df_cp["venueID"].astype(str)

df_cp["time"] = pd.to_datetime(df_cp["time"])
df_cp["city_name"] = "Tokyo"

df_cp

/tmp/ipykernel_1448755/1479321888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cp["venueID"] = df_cp["venueID"].astype(str)
/tmp/ipykernel_1448755/1479321888.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_cp["time"] = pd.to_datetime(df_cp["time"])
/tmp/ipykernel_1448755/1479321888.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cp["time"] = pd.to_datetime(df_cp["time"])

,uid,lat,lng,venueID,venue_descr,time,venue_category_id,city_name
0,114,35.714542,139.480065,4c16fdda96040f477cc473a5,Convenience Store,2012-04-03 19:12:07+00:00,4d954b0ea243a5684a65b473,Tokyo
1,114,35.700253,139.480255,4b3eae5cf964a520b4a025e3,Train Station,2012-04-03 19:35:36+00:00,4bf58dd8d48988d129951735,Tokyo
2,589,35.548963,139.784611,4b5ed39cf964a520079a29e3,Airport,2012-04-03 19:59:06+00:00,4bf58dd8d48988d1eb931735,Tokyo
3,589,35.575028,139.758786,4e014c11c65b896d116d480c,Bus Station,2012-04-03 20:01:54+00:00,4bf58dd8d48988d1fe931735,Tokyo
4,471,35.709190,139.773822,4ba88a28f964a52028df39e3,Ramen / Noodle House,2012-04-03 20:09:35+00:00,4bf58dd8d48988d1d1941735,Tokyo

In [7]:
df_cp["First_Category"] = df_cp["venue_category_id"].apply(lambda x: category_dict[x][0] if x in category_dict else "Unknown")

df_cp["Second_Category"] = df_cp["venue_category_id"].apply(
    lambda x: category_dict[x][1] if x in category_dict and len(category_dict[x]) > 1 else "Unknown"
)
df_cp["Second_Category"] = df_cp.apply(
    lambda row: row["First_Category"] if row["Second_Category"] == "Unknown" else row["Second_Category"], axis=1
)


df_cp["Third_Category"] = df_cp["venue_category_id"].apply(
    lambda x: category_dict[x][2] if x in category_dict and len(category_dict[x]) > 2 else "Unknown"
)
df_cp["Third_Category"] = df_cp.apply(
    lambda row: row["Second_Category"] if row["Third_Category"] == "Unknown" else row["Third_Category"], axis=1
)

In [8]:
df_cp

,uid,lat,lng,venueID,venue_descr,time,venue_category_id,city_name,First_Category,Second_Category,Third_Category
0,114,35.714542,139.480065,4c16fdda96040f477cc473a5,Convenience Store,2012-04-03 19:12:07+00:00,4d954b0ea243a5684a65b473,Tokyo,Retail,Convenience Store,Convenience Store
1,114,35.700253,139.480255,4b3eae5cf964a520b4a025e3,Train Station,2012-04-03 19:35:36+00:00,4bf58dd8d48988d129951735,Tokyo,Travel and Transportation,Transport Hub,Rail Station
2,589,35.548963,139.784611,4b5ed39cf964a520079a29e3,Airport,2012-04-03 19:59:06+00:00,4bf58dd8d48988d1eb931735,Tokyo,Travel and Transportation,Transport Hub,Airport
3,589,35.575028,139.758786,4e014c11c65b896d116d480c,Bus Station,2012-04-03 20:01:54+00:00,4bf58dd8d48988d1fe931735,Tokyo,Travel and Transportation,Transport Hub,Bus Station
4,471,35.709190,139.773822,4ba88a28f964a52028df39e3,Ramen / Noodle House,2012-04-03 20:09:35+00:00,4bf58dd8d48988d1d1941735,Tokyo,Dining and Drinking,Restaurant,Asian Restaurant
...,...,...,...,...,...,...,...,...,...,...,...
273498,2200,35.690803,139.700279,4b0587a6f964a5203d9e22e3,Train Station,2013-02-16 02:32:51+00:00,4bf58dd8d48988d129951735,Tokyo,Travel and Transportation,Transport Hub,Rail Station
273499,2277,35.710080,139.790999,4b82669cf964a5209ed130e3,Post Office,2013-02-16 02:33:48+00:00,4bf58dd8d48988d172941735,Tokyo,Community and Government,Government Building,Post Office
273500,2277,35.709845,139.790801,4b56c4c5f964a520c41a28e3,Subway,2013-02-16 02:34:32+00:00,4bf58dd8d48988d1fd931735,Tokyo,Travel and Transportation,Transport Hub,Metro Station
273501,326,35.656939,139.702518,4bab3456f964a5204d993ae3,Music Venue,2013-02-16 02:34:35+00:00,4bf58dd8d48988d1e9931735,Tokyo,Arts and Entertainment,Performing Arts Venue,Music Venue
273502,1050,35.704069,139.579496,4b5a7486f964a52027c628e3,Record Shop,2013-02-16 02:35:29+00:00,4bf58dd8d48988d10d951735,Tokyo,Retail,Record Store,Record Store

In [9]:
#drop lines with unknwown in either first or second category
df_cp = df_cp[(df_cp["First_Category"] != "Unknown") & (df_cp["Second_Category"] != "Unknown")]
df_cp.drop(columns=["venue_category_id"], inplace=True)
df_cp

/tmp/ipykernel_1448755/3185552217.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cp.drop(columns=["venue_category_id"], inplace=True)

,uid,lat,lng,venueID,venue_descr,time,city_name,First_Category,Second_Category,Third_Category
0,114,35.714542,139.480065,4c16fdda96040f477cc473a5,Convenience Store,2012-04-03 19:12:07+00:00,Tokyo,Retail,Convenience Store,Convenience Store
1,114,35.700253,139.480255,4b3eae5cf964a520b4a025e3,Train Station,2012-04-03 19:35:36+00:00,Tokyo,Travel and Transportation,Transport Hub,Rail Station
2,589,35.548963,139.784611,4b5ed39cf964a520079a29e3,Airport,2012-04-03 19:59:06+00:00,Tokyo,Travel and Transportation,Transport Hub,Airport
3,589,35.575028,139.758786,4e014c11c65b896d116d480c,Bus Station,2012-04-03 20:01:54+00:00,Tokyo,Travel and Transportation,Transport Hub,Bus Station
4,471,35.709190,139.773822,4ba88a28f964a52028df39e3,Ramen / Noodle House,2012-04-03 20:09:35+00:00,Tokyo,Dining and Drinking,Restaurant,Asian Restaurant
...,...,...,...,...,...,...,...,...,...,...
273498,2200,35.690803,139.700279,4b0587a6f964a5203d9e22e3,Train Station,2013-02-16 02:32:51+00:00,Tokyo,Travel and Transportation,Transport Hub,Rail Station
273499,2277,35.710080,139.790999,4b82669cf964a5209ed130e3,Post Office,2013-02-16 02:33:48+00:00,Tokyo,Community and Government,Government Building,Post Office
273500,2277,35.709845,139.790801,4b56c4c5f964a520c41a28e3,Subway,2013-02-16 02:34:32+00:00,Tokyo,Travel and Transportation,Transport Hub,Metro Station
273501,326,35.656939,139.702518,4bab3456f964a5204d993ae3,Music Venue,2013-02-16 02:34:35+00:00,Tokyo,Arts and Entertainment,Performing Arts Venue,Music Venue
273502,1050,35.704069,139.579496,4b5a7486f964a52027c628e3,Record Shop,2013-02-16 02:35:29+00:00,Tokyo,Retail,Record Store,Record Store

In [10]:
sorted(df_cp["Third_Category"].unique())

['African Restaurant',
 'Airport',
 'American Restaurant',
 'Amusement Park',
 'Animal Shelter',
 'Antique Store',
 'Apartment or Condo',
 'Aquarium',
 'Arcade',
 'Art Gallery',
 'Art Museum',
 'Arts and Crafts Store',
 'Arts and Entertainment',
 'Asian Restaurant',
 'Assisted Living',
 'Auditorium',
 'Australian Restaurant',
 'Automotive Shop',
 'BBQ Joint',
 'Bagel Shop',
 'Bakery',
 'Banking and Finance',
 'Bar',
 'Baseball Field',
 'Baseball Stadium',
 'Beach',
 'Bed and Breakfast',
 'Beer Garden',
 'Bicycle Store',
 'Bike Rental',
 'Board Store',
 'Boat or Ferry',
 'Bookstore',
 'Boutique',
 'Bowling Alley',
 'Breakfast Spot',
 'Brewery',
 'Bridal Store',
 'Bridge',
 'Burger Joint',
 'Bus Station',
 'Business and Professional Services',
 'Butcher',
 'Cafeteria',
 'Café',
 'Cajun and Creole Restaurant',
 'Camera Store',
 'Campground',
 'Candy Store',
 'Capitol Building',
 'Car Dealership',
 'Car Wash and Detail',
 'Caribbean Restaurant',
 'Casino',
 'Cemetery',
 'Cheese Store',
 "Children's Clothing Store",
 'Church',
 'City',
 'City Hall',
 'Climbing Gym',
 'Clothing Store',
 'Cocktail Bar',
 'Coffee Shop',
 'College and University',
 'Comedy Club',
 'Concert Hall',
 'Conference Room',
 'Convenience Store',
 'Convention Center',
 'Cosmetics Store',
 'Courthouse',
 'Coworking Space',
 'Cupcake Shop',
 'Dance Studio',
 'Daycare',
 'Deli',
 'Dentist',
 'Department Store',
 'Design Studio',
 'Dessert Shop',
 'Diner',
 'Distillery',
 'Dive Bar',
 "Doctor's Office",
 'Dog Park',
 'Donut Shop',
 'Dumpling Restaurant',
 'Eastern European Restaurant',
 'Education',
 'Electronics Store',
 'Embassy or Consulate',
 'Emergency Room',
 'Event Space',
 'Eyecare Store',
 'Factory',
 'Fair',
 'Falafel Restaurant',
 'Farm',
 'Farmers Market',
 'Fashion Accessories Store',
 'Fast Food Restaurant',
 'Field',
 'Financial or Legal Service',
 'Fish Market',
 'Fish and Chips Shop',
 'Flea Market',
 'Flower Store',
 'Food Court',
 'Food Truck',
 'Food and Beverage Retail',
 'Football Stadium',
 'French Restaurant',
 'Fried Chicken Joint',
 'Fuel Station',
 'Funeral Home',
 'Furniture and Home Store',
 'Gaming Cafe',
 'Garden',
 'Garden Center',
 'Gastropub',
 'Gay Bar',
 'General Entertainment',
 'General Travel',
 'German Restaurant',
 'Gift Store',
 'Golf Course',
 'Gourmet Store',
 'Government Building',
 'Grocery Store',
 'Gym',
 'Gym Pool',
 'Gym and Studio',
 'Hair Salon',
 'Harbor or Marina',
 'Hardware Store',
 'Hiking Trail',
 'Historic and Protected Site',
 'History Museum',
 'Hobby Store',
 'Home (private)',
 'Hookah Bar',
 'Hospital',
 'Hostel',
 'Hot Dog Joint',
 'Hot Spring',
 'Hotel',
 'Hotel Bar',
 'Housing Development',
 'Ice Cream Parlor',
 'Indian Restaurant',
 'Indie Movie Theater',
 'Indie Theater',
 'Internet Cafe',
 'Italian Restaurant',
 'Jewelry Store',
 'Juice Bar',
 'Karaoke Bar',
 'Lake',
 'Landmarks and Outdoors',
 'Latin American Restaurant',
 'Laundry Service',
 'Law Enforcement and Public Safety',
 'Library',
 'Light Rail Station',
 'Lighthouse',
 'Lingerie Store',
 'Liquor Store',
 'Lounge',
 'Market',
 'Martial Arts Dojo',
 'Medical Center',
 'Medical Lab',
 'Mediterranean Restaurant',
 'Meeting Room',
 "Men's Store",
 'Metro Station',
 'Mexican Restaurant',
 'Middle Eastern Restaurant',
 'Military',
 'Miscellaneous Store',
 'Mobile Phone Store',
 'Monument',
 'Moroccan Restaurant',
 'Mosque',
 'Motel',
 'Motorcycle Dealership',
 'Mountain',
 'Movie Theater',
 'Moving Target',
 'Multiplex',
 'Museum',
 'Music School',
 'Music Store',
 'Music Venue',
 'Nail Salon',
 'Neighborhood',
 'Newsstand',
 'Night Club',
 'Nightlife Spot',
 'Non-Profit Organization',
 'Nursery School',
 'Office',
 'Office Supply Store',
 'Opera House',
 'Other Great Outdoors',
 'Other Nightlife',
 'Park',
 'Parking',
 'Performing Arts Venue',
 'Pet Supplies Store',
 'Pharmacy',
 'Photography Lab',
 'Piano Bar',
 'Pier',
 'Pizzeria',
 'Planetarium',
 'Platform',
 'Playground',
 'Plaza',
 'Polling Place',
 'Pool Hall',
 'Portuguese Restaurant',
 'Post Office',
 'Primary and Secondary School',
 'Pub',
 'Public Art',
 'Public Transportation',
 'Race Track',
 'Radio Station',
 'Rail Station',
 'Record Store',
 'Recycling Facility',
 'Rental Car Location',
 'Resort',
 'Rest Area',
 'Restaurant',
 'Retail',
 'River',
 'Road',
 'Sake Bar',
 'Salad Restaurant',
 'Sandwich Spot',
 'Scandinavian Restaurant',
 'Scenic Lookout',
 'Science Museum',
 'Sculpture Garden',
 'Seafood Restaurant',
 'Shoe Store',
 'Shopping Mall',
 'Shrine',
 'Skate Park',
 'Skating Rink',
 'Ski Resort and Area',
 'Smoke Shop',
 'Snack Place',
 'Soccer Field',
 'Soccer Stadium',
 'Soup Spot',
 'Southern Food Restaurant',
 'Spa',
 'Spanish Restaurant',
 'Speakeasy',
 'Spiritual Center',
 'Sporting Goods Retail',
 'Sports Bar',
 'Sports and Recreation',
 'Stable',
 'Stadium',
 'Steakhouse',
 'Storage Facility',
 'Strip Club',
 'Structure',
 'Swimming',
 'Swiss Restaurant',
 'Synagogue',
 'Tanning Salon',
 'Taxi',
 'Tea Room',
 'Tech Startup',
 'Temple',
 'Tennis',
 'Theater',
 'Tourist Information and Service',
 'Toy Store',
 'Track',
 'Track Stadium',
 'Trade School',
 'Train',
 'Travel Agency',
 'Travel Lounge',
 'Travel and Transportation',
 'Turkish Restaurant',
 'Vegan and Vegetarian Restaurant',
 'Veterinarian',
 'Video Games Store',
 'Video Store',
 'Vineyard',
 'Vintage and Thrift Store',
 'Water Park',
 'Whisky Bar',
 'Wine Bar',
 'Wine Store',
 'Winery',
 'Wings Joint',
 "Women's Store",
 'Yoga Studio',
 'Zoo']

In [11]:
#from df_cp drop lines that have as Third_Category  Meeting Room, Conference Room, Office, Home (private) Apartment or Condo
df_cp = df_cp[~df_cp["Third_Category"].isin(["Meeting Room", "Conference Room", "Office", "Home (private)", "Apartment or Condo"])]
df_cp

,uid,lat,lng,venueID,venue_descr,time,city_name,First_Category,Second_Category,Third_Category
0,114,35.714542,139.480065,4c16fdda96040f477cc473a5,Convenience Store,2012-04-03 19:12:07+00:00,Tokyo,Retail,Convenience Store,Convenience Store
1,114,35.700253,139.480255,4b3eae5cf964a520b4a025e3,Train Station,2012-04-03 19:35:36+00:00,Tokyo,Travel and Transportation,Transport Hub,Rail Station
2,589,35.548963,139.784611,4b5ed39cf964a520079a29e3,Airport,2012-04-03 19:59:06+00:00,Tokyo,Travel and Transportation,Transport Hub,Airport
3,589,35.575028,139.758786,4e014c11c65b896d116d480c,Bus Station,2012-04-03 20:01:54+00:00,Tokyo,Travel and Transportation,Transport Hub,Bus Station
4,471,35.709190,139.773822,4ba88a28f964a52028df39e3,Ramen / Noodle House,2012-04-03 20:09:35+00:00,Tokyo,Dining and Drinking,Restaurant,Asian Restaurant
...,...,...,...,...,...,...,...,...,...,...
273498,2200,35.690803,139.700279,4b0587a6f964a5203d9e22e3,Train Station,2013-02-16 02:32:51+00:00,Tokyo,Travel and Transportation,Transport Hub,Rail Station
273499,2277,35.710080,139.790999,4b82669cf964a5209ed130e3,Post Office,2013-02-16 02:33:48+00:00,Tokyo,Community and Government,Government Building,Post Office
273500,2277,35.709845,139.790801,4b56c4c5f964a520c41a28e3,Subway,2013-02-16 02:34:32+00:00,Tokyo,Travel and Transportation,Transport Hub,Metro Station
273501,326,35.656939,139.702518,4bab3456f964a5204d993ae3,Music Venue,2013-02-16 02:34:35+00:00,Tokyo,Arts and Entertainment,Performing Arts Venue,Music Venue
273502,1050,35.704069,139.579496,4b5a7486f964a52027c628e3,Record Shop,2013-02-16 02:35:29+00:00,Tokyo,Retail,Record Store,Record Store

In [12]:
sorted(list(df_cp["Second_Category"].unique()))

['Amusement Park',
 'Animal Shelter',
 'Antique Store',
 'Aquarium',
 'Arcade',
 'Art Gallery',
 'Arts and Crafts Store',
 'Arts and Entertainment',
 'Assisted Living',
 'Auditorium',
 'Automotive Retail',
 'Automotive Service',
 'Automotive Shop',
 'Bagel Shop',
 'Bakery',
 'Bar',
 'Baseball',
 'Beach',
 'Bike Rental',
 'Board Store',
 'Boat or Ferry',
 'Bookstore',
 'Boutique',
 'Bowling Alley',
 'Breakfast Spot',
 'Brewery',
 'Bridge',
 'Business and Professional Services',
 'Cafe, Coffee, and Tea House',
 'Cafeteria',
 'Campground',
 'Casino',
 'Cemetery',
 'Child Care Service',
 'Comedy Club',
 'Computers and Electronics Retail',
 'Convenience Store',
 'Convention Center',
 'Cosmetics Store',
 'Dentist',
 'Department Store',
 'Design Studio',
 'Dessert Shop',
 'Distillery',
 'Donut Shop',
 'Education',
 'Emergency Service',
 'Event Space',
 'Eyecare Store',
 'Factory',
 'Fair',
 'Farm',
 'Fashion Retail',
 'Field',
 'Financial Service',
 'Financial or Legal Service',
 'Flea Market',
 'Flower Store',
 'Food Court',
 'Food Truck',
 'Food and Beverage Retail',
 'Fuel Station',
 'Funeral Home',
 'Furniture and Home Store',
 'Gaming Cafe',
 'Garden',
 'Garden Center',
 'General Entertainment',
 'General Travel',
 'Gift Store',
 'Golf',
 'Government Building',
 'Gym and Studio',
 'Harbor or Marina',
 'Hardware Store',
 'Health and Beauty Service',
 'Hiking Trail',
 'Historic and Protected Site',
 'Hobby Store',
 'Hospital',
 'Hot Spring',
 'Housing Development',
 'Internet Cafe',
 'Juice Bar',
 'Lake',
 'Landmarks and Outdoors',
 'Laundry Service',
 'Library',
 'Lighthouse',
 'Lodging',
 'Market',
 'Martial Arts Dojo',
 'Medical Center',
 'Medical Lab',
 'Miscellaneous Store',
 'Monument',
 'Mountain',
 'Movie Theater',
 'Moving Target',
 'Museum',
 'Music Store',
 'Newsstand',
 'Night Club',
 'Nightlife Spot',
 'Office',
 'Office Supply Store',
 'Organization',
 'Other Great Outdoors',
 'Other Nightlife',
 'Park',
 'Parking',
 'Performing Arts Venue',
 'Pet Supplies Store',
 'Pharmacy',
 'Photography Service',
 'Physician',
 'Pier',
 'Planetarium',
 'Platform',
 'Plaza',
 'Polling Place',
 'Pool Hall',
 'Public Art',
 'Race Track',
 'Racquet Sports',
 'Radio Station',
 'Record Store',
 'Recycling Facility',
 'Rest Area',
 'Restaurant',
 'Retail',
 'River',
 'Road',
 'Running and Track',
 'Scenic Lookout',
 'Sculpture Garden',
 'Shopping Mall',
 'Skating',
 'Smoke Shop',
 'Snack Place',
 'Snow Sports',
 'Soccer',
 'Spiritual Center',
 'Sporting Goods Retail',
 'Sports and Recreation',
 'Stable',
 'Stadium',
 'States and Municipalities',
 'Storage Facility',
 'Strip Club',
 'Structure',
 'Tourist Information and Service',
 'Toy Store',
 'Train',
 'Transport Hub',
 'Transportation Service',
 'Travel Agency',
 'Travel Lounge',
 'Travel and Transportation',
 'Veterinarian',
 'Video Store',
 'Vineyard',
 'Vintage and Thrift Store',
 'Water Park',
 'Water Sports',
 'Winery',
 'Zoo']

In [14]:
#from df_cp drop lines whose Second Category is transportation or strange things
df_cp = df_cp[~df_cp["Second_Category"].isin(["Train", "Transport Hub", "Transportation Service", "Travel and Transportation", 
                                              "Boat or Ferry", "Platform", "Road",
                                              "Island", "River", "Housing Development",
                                              ])]

In [15]:
df_cp["time"].min(), df_cp["time"].max()

(Timestamp('2012-04-03 19:12:07+0000', tz='UTC'),
 Timestamp('2013-02-16 02:35:29+0000', tz='UTC'))

In [16]:
df_cp_venues = df_cp[["venueID", "lat", "lng", "First_Category", "Second_Category", "Third_Category"]].drop_duplicates()

df_cp_venues

,venueID,lat,lng,First_Category,Second_Category,Third_Category
0,4c16fdda96040f477cc473a5,35.714542,139.480065,Retail,Convenience Store,Convenience Store
4,4ba88a28f964a52028df39e3,35.709190,139.773822,Dining and Drinking,Restaurant,Asian Restaurant
5,4d69a46cde28224b27ff45be,35.609929,139.825659,Landmarks and Outdoors,Bridge,Bridge
7,4d1bcae9f8ca236a2ff7f030,35.669933,139.825227,Landmarks and Outdoors,Field,Field
8,4d4f756eedc68eec0391b1a4,35.685405,139.826665,Landmarks and Outdoors,Bridge,Bridge
...,...,...,...,...,...,...
273455,4e2a771bc65bcaf400243596,35.749621,139.585038,Travel and Transportation,Parking,Parking
273467,50ecf5abe4b0f4fa6f7dafda,35.678494,139.741405,Landmarks and Outdoors,Structure,Structure
273471,4bd91d102e6f0f47d7d20908,35.668426,139.716890,Dining and Drinking,Restaurant,Restaurant
273482,4b91d257f964a520a8d933e3,35.750061,139.587119,Dining and Drinking,"Cafe, Coffee, and Tea House",Coffee Shop
273488,4bda94b8c79cc928e5327fe9,35.703205,139.579236,Retail,Food and Beverage Retail,Food and Beverage Retail

In [17]:
from collections import defaultdict


venueID2second_category = defaultdict(list)

for index, row in df_cp.iterrows():
    venueID2second_category[row["venueID"]].append(row["Second_Category"])


venueID2second_category = {k: list(set(v)) for k, v in venueID2second_category.items()}
venueID2second_category

{'4c16fdda96040f477cc473a5': ['Convenience Store'],
 '4ba88a28f964a52028df39e3': ['Restaurant'],
 '4d69a46cde28224b27ff45be': ['Bridge'],
 '4d1bcae9f8ca236a2ff7f030': ['Field'],
 '4d4f756eedc68eec0391b1a4': ['Bridge'],
 '4b5a86faf964a520d3c928e3': ['Government Building'],
 '4ea03c1c7beb6623c1449ee0': ['Convenience Store'],
 '4b5d2ad2f964a520535529e3': ['Convenience Store'],
 '4b568200f964a520571328e3': ['Education'],
 '4e65fe028877954de9acd8bf': ['Monument'],
 '4b65494af964a520f4eb2ae3': ['Bridge'],
 '4bf47064706e20a1ef5ca998': ['Cafe, Coffee, and Tea House', 'Restaurant'],
 '4b5ef108f964a520d89e29e3': ['Gym and Studio'],
 '4b526ed4f964a5201b7d27e3': ['Park'],
 '4f7b7210e4b0de4ca14a9af8': ['Food and Beverage Retail'],
 '4b553487f964a5208fde27e3': ['Food and Beverage Retail'],
 '4b7d7de1f964a5200bc22fe3': ['Shopping Mall', 'Other Nightlife'],
 '4b98e261f964a520365435e3': ['Food and Beverage Retail'],
 '4b0587a6f964a520529e22e3': ['Shopping Mall'],
 '4b72c558f964a520d2872de3': ['Restaurant'],
 '4b5829f4f964a520a44c28e3': ['Cafe, Coffee, and Tea House'],
 '4b63fae9f964a520b4992ae3': ['Other Great Outdoors'],
 '4b5e4928f964a520c68729e3': ['Restaurant'],
 '4b802cabf964a520495930e3': ['Park'],
 '4b5a3b6cf964a52026b628e3': ['Restaurant'],
 '4c34ee3d09a99c749b4a0c2a': ['Park'],
 '4b6545c5f964a52064eb2ae3': ['Other Great Outdoors'],
 '4b6f881bf964a5209cf42ce3': ['Park'],
 '4ee8aab693ad8b68e9b0c649': ['Food and Beverage Retail'],
 '4ba5977af964a520d61439e3': ['Other Great Outdoors'],
 '4c8a6ed952a98cfa1e912ce9': ['Park'],
 '4b9f1364f964a520ab1237e3': ['Cafe, Coffee, and Tea House'],
 '4c31783866e40f477521c58b': ['Bridge'],
 '4e5075afd164978659da0746': ['Toy Store'],
 '4ba56d50f964a520f70539e3': ['Structure'],
 '4b57b024f964a520fd3b28e3': ['Bridge'],
 '4b593260f964a520f58028e3': ['Government Building'],
 '4b746edbf964a5204fdc2de3': ['Convenience Store'],
 '4c0cdca798102d7fd838e106': ['Restaurant'],
 '4b565e9ff964a5208a0d28e3': ['Cafe, Coffee, and Tea House'],
 '4b5db97ff964a5209a6829e3': ['Convenience Store'],
 '4b56fc09f964a520c52128e3': ['Other Great Outdoors'],
 '4f72aabce4b0a4b289c3b1c6': ['Convenience Store'],
 '4be3c37799feb713c51882f6': ['Food and Beverage Retail'],
 '4b9909daf964a520545d35e3': ['Convenience Store'],
 '4b56c2aef964a520881a28e3': ['Miscellaneous Store'],
 '4c9c4ed69c48236a82094dee': ['Convenience Store'],
 '4b5755cdf964a520153228e3': ['Video Store'],
 '4bc8508214d79521afc768e9': ['Restaurant'],
 '4c1b83960137952198e446f3': ['Bridge'],
 '4cc8d012d338236ab6339f7c': ['Convenience Store'],
 '4b8a02f4f964a5208e5b32e3': ['Miscellaneous Store'],
 '4bea4a646295c9b68a4d8608': ['Bridge'],
 '4b5b1051f964a5209de128e3': ['Bridge'],
 '4bb53d352ea195216e3baa2f': ['Bridge'],
 '4b5a46fbf964a5208eb928e3': ['Cafe, Coffee, and Tea House'],
 '4b59d5f4f964a520f99a28e3': ['Restaurant'],
 '4f5db79ee4b01f8f4df7fd0e': ['Bridge'],
 '4e6ea5d11f6e63a4ea6fb39f': ['Smoke Shop'],
 '4d1a7b6f02a66dcb3d806065': ['Restaurant'],
 '4c47c32e1ddec9287f949e32': ['Convenience Store'],
 '4b972b47f964a520c9fa34e3': ['Government Building'],
 '4b73ecf6f964a52059c02de3': ['Convenience Store'],
 '4bf5fbf694b2a59343cfacee': ['Cafe, Coffee, and Tea House'],
 '4b986f7ef964a5201a4235e3': ['Park'],
 '4c7523466f789c74742f494c': ['Museum'],
 '4b9e100ff964a520d2c836e3': ['Bridge'],
 '4f0d071ee4b04a8cd74674ae': ['Structure'],
 '4b54ea63f964a520efd227e3': ['Movie Theater'],
 '4f751002e4b06c81e0667de6': ['Education'],
 '4e534dd1e4cd13d1047c825f': ['Parking'],
 '4b5e638ef964a520a58c29e3': ['Park'],
 '4be956986af1ef3b2bbf1b96': ['Convenience Store'],
 '4b552568f964a520cadc27e3': ['Structure'],
 '4b8918fff964a5208d1c32e3': ['Convenience Store'],
 '4bc143b1461576b007ca7b32': ['Park'],
 '4d1e58a8b69c6dcb78cc5c95': ['Spiritual Center'],
 '4dc642e5fa76d685cdf6822c': ['Other Great Outdoors'],
 '4b5982c0f964a520a28a28e3': ['Restaurant'],
 '4baed581f964a520c2db3be3': ['Park'],
 '4bebcfccb3352d7f53db56d2': ['Restaurant'],
 '4eb101f19adf1abeff96b11a': ['Convenience Store'],
 '4b5989c8f964a520a18b28e3': ['Convenience Store'],
 '4ecf26c34690a03b5be18c46': ['Education'],
 '4b67d893f964a520235f2be3': ['Convenience Store'],
 '4b7e1ecef964a52071e32fe3': ['Cafe, Coffee, and Tea House'],
 '4ec9e7bfcc21b428e5e3e370': ['Structure'],
 '4f0d1e8be4b0d2af7195dc7c': ['Convenience Store'],
 '4c8872b2a0ffb60cb47522c5': ['Shopping Mall'],
 '4c1a0d22838020a1c090e661': ['Spiritual Center'],
 '4df1904ae4cda09e6d9b27fb': ['Restaurant'],
 '4bbac03d7421a593ed2dc440': ['Convenience Store'],
 '4c103a4781e976b042e50eeb': ['Food and Beverage Retail'],
 '4b59250df964a520d37e28e3': ['Convenience Store'],
 '4cf6d57971538cfa38c8b72e': ['Hiking Trail'],
 '4d104081c3dc3704910f3874': ['Shopping Mall'],
 '4b76248cf964a520ac3f2ee3': ['Historic and Protected Site'],
 '4b541c27f964a52080b227e3': ['Education'],
 '4b7f961bf964a5208c3530e3': ['Garden'],
 '4ea765127ee5c765189401dd': ['Education'],
 '4b63ca9ef964a520c5912ae3': ['Department Store'],
 '4cb0af673f0676b0a826fc0c': ['Historic and Protected Site'],
 '4b935fedf964a520d94134e3': ['Spiritual Center'],
 '4d76c3eb41526ea80615598a': ['Cafe, Coffee, and Tea House'],
 '4b7c17c1f964a520787c2fe3': ['Historic and Protected Site'],
 '4f6d7593e4b03b575c3613b1': ['Art Gallery'],
 '4b569977f964a520551628e3': ['Monument'],
 '4e5ca79b091a7a61047f697b': ['Hiking Trail', 'Education'],
 '4b6260a5f964a5200f452ae3': ['Restaurant'],
 '4f0d0bf0e4b0d2af7185d0cb': ['Physician'],
 '4b558892f964a520b9e627e3': ['Event Space'],
 '4f729013e4b0905384b2e359': ['Other Great Outdoors'],
 '4b7a93d0f964a520fb312fe3': ['Historic and Protected Site'],
 '4b5dd77af964a5200f6f29e3': ['Cafe, Coffee, and Tea House'],
 '4c93701e1221b1f7defb19e2': ['Night Club'],
 '4d75e90b8d7e236a6f07b028': ['Water Park'],
 '4d5f51ee039188bfa3cb7123': ['Lake'],
 '4c1341a0a9c220a10c86559d': ['Plaza'],
 '4c38e3001e06d13a929f783e': ['Spiritual Center'],
 '4b7bee49f964a5205c742fe3': ['Historic and Protected Site'],
 '4b5d8811f964a520596029e3': ['Computers and Electronics Retail'],
 '4b62271cf964a520cf382ae3': ['Cafe, Coffee, and Tea House'],
 '4b7bdc24f964a52009712fe3': ['Education'],
 '4f7423f4e4b0c1f44634bb7c': ['Food and Beverage Retail'],
 '4c86f6fee602b1f7877fc47a': ['Structure'],
 '4b812faff964a520c09930e3': ['Monument'],
 '4d463248c3e5f04d8c13ac20': ['Smoke Shop'],
 '4b4fbac7f964a520ea1227e3': ['Cafe, Coffee, and Tea House'],
 '4ec09a4fbe7b04923ccd270d': ['Sculpture Garden'],
 '4b59675bf964a5204e8728e3': ['Structure'],
 '4e5b86ac1fc7864a236b0ed2': ['Education'],
 '4b7d736ef964a5202abf2fe3': ['Historic and Protected Site'],
 '4b9c81a6f964a5202d6d36e3': ['Plaza'],
 '4b8c3669f964a52068c432e3': ['Restaurant'],
 '4bb200cbf964a5200fb13ce3': ['Park'],
 '4b7e4a1ef964a5207ae82fe3': ['Arts and Crafts Store'],
 '4e292cfc45ddfe8f9df97d0f': ['Bakery'],
 '4be4d3b2d4f7c9b6c7c82420': ['Stadium'],
 '4dbce1ca43a1d8504b98d0a5': ['Education'],
 '4c318f3266e40f47273bc58b': ['Gym and Studio'],
 '4bd14e19a8b3a593a898655f': ['Structure'],
 '4ba6108bf964a5203b3139e3': ['Convenience Store'],
 '4f7a4d65e4b01187874460a6': ['Child Care Service', 'Education'],
 '4b54fd0ff964a520c4d627e3': ['Convenience Store'],
 '4c71f0a9376da093d156a5c6': ['Government Building'],
 '4b724d52f964a52028772de3': ['Park'],
 '4e2bc33db0fbc2edac25d40e': ['Government Building'],
 '4c6a01052c29d13af6df0c41': ['Cafeteria'],
 '4e313b86922ea20b3461a8ca': ['Smoke Shop'],
 '4b7e3467f964a520fde52fe3': ['Office'],
 '4b779bc6f964a520c9a32ee3': ['Food and Beverage Retail'],
 '4e8024cfbe7bf891816f6e94': ['Performing Arts Venue'],
 '4b973885f964a5208ffc34e3': ['Convenience Store'],
 '4c69c6f62c29d13a002e0c41': ['Cafe, Coffee, and Tea House'],
 '4b0587a1f964a5209b9d22e3': ['Park'],
 '4dfc242962846d918b936ca7': ['Plaza'],
 '4f28c9aee4b0abca063d049a': ['Spiritual Center'],
 '4bbd20d3a8cf76b0d977b1fd': ['Restaurant'],
 '4c004bb4369476b0de358f1f': ['Cafe, Coffee, and Tea House'],
 '4b5c3414f964a520382729e3': ['Bookstore'],
 '4b64fbabf964a520acdd2ae3': ['Miscellaneous Store'],
 '4b6f807af964a5203ef32ce3': ['Education'],
 '4b6f80abf964a5204af32ce3': ['Education'],
 '4b74eaebf964a52009f82de3': ['Food and Beverage Retail'],
 '4c26caa65c5ca59308e546fe': ['Restaurant'],
 '4b662f05f964a520f5172be3': ['Government Building'],
 '4cd4cd5dfb59548186bada50': ['Museum'],
 '4c481f4f31e41b8de2e94e35': ['Furniture and Home Store'],
 '4ca8107cb0b8236acc2bb0e6': ['Restaurant'],
 '4ba24245f964a520b2e737e3': ['Restaurant'],
 '4dfebb9588779f08f996a895': ['Restaurant'],
 '4b729571f964a520647f2de3': ['Cafe, Coffee, and Tea House'],
 '4b64e70ef964a520acd82ae3': ['Park'],
 '4bb16e7af964a52009933ce3': ['Restaurant'],
 '4b592b24f964a520ee7f28e3': ['Structure'],
 '4c7b25c7566db60ce2544a0e': ['Restaurant'],
 '4b88a474f964a520520632e3': ['Art Gallery'],
 '4b86316af964a520488231e3': ['Cafe, Coffee, and Tea House'],
 '4bc14fc6abf495215bfcc093': ['Restaurant'],
 '4b71529df964a52019412de3': ['Restaurant'],
 '4b9a0126f964a520b09a35e3': ['Restaurant'],
 '4b56fd40f964a520fa2128e3': ['Restaurant'],
 '4d93c45f45ae5481af21f6eb': ['Cafe, Coffee, and Tea House'],
 '4b5fd552f964a52041ce29e3': ['Cafe, Coffee, and Tea House'],
 '4c050a03f56c2d7fde021f66': ['Education'],
 '4f69e57fe4b00d930a3dd075': ['Government Building'],
 '4ddf3ba8d22d728b20c37aa7': ['Education'],
 '4f6227b2e4b073ddcaba153f': ['Bar'],
 '4b95d003f964a52032b434e3': ['Restaurant'],
 '4b7df9f5f964a5201add2fe3': ['Restaurant'],
 '4b77d168f964a5205aab2ee3': ['Food and Beverage Retail'],
 '4bdd0a1e8f53d13a59a9eb8f': ['Restaurant'],
 '4b5860faf964a520135528e3': ['Education'],
 '4cc183bbf4448cfab2275798': ['Restaurant'],
 '4db94096f7b1b4c54f4ca914': ['Restaurant'],
 '4c5f717813791b8d2e9a4daf': ['Restaurant'],
 '4b9b3b0df964a5203afb35e3': ['Food and Beverage Retail'],
 '4d39872ebeb7b1f70d1de071': ['Restaurant'],
 '4db107b91e729fcc564a5ea1': ['Garden'],
 '4b8f8592f964a520e35633e3': ['Restaurant'],
 '4d3196108250f04d52f0eae0': ['Restaurant'],
 '4db386ae43a1369cb5a6920e': ['Park'],
 '4b55670ff964a52071e327e3': ['Computers and Electronics Retail'],
 '4bc03e8374a9a593b3d6cff6': ['Restaurant'],
 '4e3a125ad164c429b7276bf8': ['Cafe, Coffee, and Tea House'],
 '4b6224d7f964a52049382ae3': ['Convenience Store'],
 '4bf4d50fe5eba593bb242090': ['Restaurant'],
 '4ce9ecd4f3bda143d613c3e4': ['Structure'],
 '4b62baa0f964a52084502ae3': ['Restaurant'],
 '4b5bd76ef964a520411929e3': ['Bridge'],
 '4ba056aef964a5202d6937e3': ['Plaza'],
 '4b59614cf964a520968628e3': ['Restaurant'],
 '4bfe3739f61dc9b6c41ea0de': ['Restaurant'],
 '4b6b9d30f964a5209a122ce3': ['Restaurant'],
 '4bce6e1dc564ef3bed5feef0': ['Restaurant'],
 '4b5d0d6bf964a520845029e3': ['Restaurant'],
 '4f7bbd8ae4b066eb2305db85': ['Restaurant'],
 '4b986888f964a520bb4035e3': ['Restaurant'],
 '4e6987f518381ea1bd82e0db': ['Restaurant'],
 '4b6fed97f964a52057002de3': ['Restaurant'],
 '4b76269cf964a5203c402ee3': ['Historic and Protected Site'],
 '4b57dbb2f964a520154428e3': ['Restaurant'],
 '4ccfca1c6449a09309acc6cf': ['Restaurant'],
 '4b7fb37af964a520a63930e3': ['Cafe, Coffee, and Tea House'],
 '4b57f67ef964a5206a4728e3': ['Park'],
 '4b55b56af964a520b5ec27e3': ['Video Store'],
 '4c95aa48f6c8ef3b0bf27dcf': ['Museum'],
 '4d00bfd821ea6ea80472439f': ['Restaurant'],
 '4f2738dbe4b012e031e3810c': ['Convenience Store'],
 '4dd35107b3ad6786c6f4ab39': ['Restaurant'],
 '4b63afedf964a520248c2ae3': ['Restaurant'],
 '4b63e8cdf964a520b0962ae3': ['Hobby Store'],
 '4b6a77acf964a52002d62be3': ['Cafe, Coffee, and Tea House'],
 '4c3a9587be4620a1a9210b13': ['Restaurant'],
 '4b572309f964a520d32728e3': ['Education'],
 '4b67ad9cf964a520915a2be3': ['Restaurant'],
 '4b5aade9f964a5208bd028e3': ['Park'],
 '4e4e6c8c62e14b77e38cdf57': ['Restaurant'],
 '4b6cdfa0f964a520c45a2ce3': ['Restaurant'],
 '4df18fdfd4c01ff6b2e43813': ['Education'],
 '4cfdd3f0f7b560fc1c2941b7': ['Restaurant'],
 '4bb485229af3b713b34c8c28': ['Restaurant'],
 '4b654f88f964a520c0ec2ae3': ['Restaurant'],
 '4f0fb413e4b0253d4afed685': ['Restaurant'],
 '4f631fbce4b09987d00aac6f': ['Restaurant'],
 '4b5672e7f964a520d31028e3': ['Education'],
 '4bc9d4b53740b71398505f65': ['Convenience Store'],
 '4d78a21c71a68cfa88320886': ['Health and Beauty Service'],
 '4bf635815e800f475304e7d4': ['Structure'],
 '4ecb16a6f790bc9a80d4f748': ['Cafe, Coffee, and Tea House'],
 '4e256f9018388c58be2b8ca6': ['Restaurant'],
 '4b6952dbf964a520cf9e2be3': ['Restaurant'],
 '4b8dd471f964a5209d0f33e3': ['Food Truck'],
 '4b73ca50f964a520eebb2de3': ['Field'],
 '4b625fcbf964a520e6442ae3': ['Cafe, Coffee, and Tea House'],
 '4ba85cb1f964a52014d839e3': ['Restaurant'],
 '4b7be1aff964a520f4712fe3': ['Cafe, Coffee, and Tea House'],
 '4cf4f0646195721e6aaa54c1': ['Education'],
 '4b625e3cf964a5209a442ae3': ['Government Building'],
 '4c2f0ceb7cc0c9b6ac12eb9a': ['Restaurant'],
 '4b4ed7cef964a52039f626e3': ['Video Store'],
 '4b5fb5fdf964a5206dc929e3': ['Bridge'],
 '4b9760def964a520900135e3': ['Lodging'],
 '4b563c1af964a520af0628e3': ['Restaurant'],
 '4d357a2b280e2c0f12e159bc': ['Education'],
 '4bd113bfcaff95212c3cd0f0': ['Restaurant'],
 '4ba5bcf8f964a520561f39e3': ['Gift Store'],
 '4ea5579b9a527d6518427a99': ['Restaurant'],
 '4b752542f964a5201bff2de3': ['Sporting Goods Retail'],
 '4b5687b0f964a520241428e3': ['Bridge'],
 '4c8e3167a8de224bbc332501': ['Bridge'],
 '4baec495f964a52060d63be3': ['Restaurant'],
 '4ca06234542b224b2d4605a0': ['Restaurant'],
 '4cd3ebdc607a6dcbfd171254': ['Bar'],
 '4c3e7e9cdb3b1b8d06986595': ['Restaurant'],
 '4b5837b9f964a5205c4e28e3': ['Bookstore'],
 '4f7bc57ee4b06a80ab476b0b': ['Restaurant'],
 '4c9989ac80958cfa177a3bd4': ['Restaurant'],
 '4eba2442722edc0eaf124041': ['Education'],
 '4f600caae4b0d461002d3f05': ['Restaurant'],
 '4f57198be4b084fcb1a84c70': ['Restaurant'],
 '4b604713f964a52050dd29e3': ['Bridge'],
 '4f6455ffe4b0dc771fde9770': ['Restaurant'],
 '4bb6d00bf562ef3bfdc93097': ['Restaurant'],
 '4b597a58f964a520908928e3': ['Cafe, Coffee, and Tea House'],
 '4b53d300f964a5207bac27e3': ['Restaurant'],
 '4b5e8295f964a520459129e3': ['Restaurant'],
 '4e7d4a53f5b924f463f6c7fe': ['Restaurant'],
 '4bada437f964a520ae603be3': ['Bridge'],
 '4b5bc476f964a520fe1429e3': ['Museum'],
 '4b6809ddf964a520d5642be3': ['Bridge'],
 '4de83103fa76fd11689b500c': ['Structure'],
 '4c207c17920076b0e543c6e9': ['Restaurant'],
 '4bbc5648afe1b7134743304b': ['Restaurant'],
 '4b5903bef964a520887828e3': ['Garden'],
 '4d760c072140721e4752cb3d': ['Miscellaneous Store'],
 '4b074565f964a5200dfb22e3': ['Education'],
 '4b626c66f964a5200f472ae3': ['Restaurant'],
 '4bb69f63941ad13a5bc41fe3': ['Cafe, Coffee, and Tea House'],
 '4f546a90e4b0b5d9df9fd7ce': ['Bar'],
 '4ca5598876d3a093488df76a': ['Restaurant'],
 '4d073fe89d33a143cec0ca78': ['Restaurant'],
 '4d0604767ee8a0900caaf254': ['Bridge'],
 '4f4a73d5e4b0156c30d49a15': ['Bar'],
 '4b595d59f964a520318628e3': ['Structure'],
 '4b5face3f964a52098c729e3': ['Restaurant'],
 '4f7bcac4e4b0726c38da45d4': ['Government Building'],
 '4d75b31bb8e28cfa6a26fc66': ['Restaurant'],
 '4c1d94e2e9c4ef3be2fe45aa': ['Restaurant'],
 '4e142dc2483bfda2e0a35a52': ['Shopping Mall'],
 '4b78e263f964a52070e52ee3': ['Spiritual Center'],
 '4b5d74aaf964a520865d29e3': ['Computers and Electronics Retail'],
 '4ba48621f964a52041a238e3': ['Financial Service'],
 '4cd4e23d122ba14309b828a1': ['Library'],
 '4b88ee77f964a5200b1432e3': ['Shopping Mall'],
 '4b57e8bdf964a520eb4528e3': ['Library'],
 '4b809226f964a520b87d30e3': ['Park'],
 '4f79adf7e4b0ca8cfefe3e33': ['Other Great Outdoors'],
 '4d92b5ddb327370426748825': ['Cafe, Coffee, and Tea House'],
 '4bea6d01415e20a12300e5bb': ['Miscellaneous Store'],
 '4c4a7dae712ac9282cd9876b': ['General Travel'],
 '4eb1e91f10814a0a5c9ca3e3': ['Spiritual Center'],
 '4b57cf2af964a5201f4228e3': ['Restaurant'],
 '4b598022f964a5204f8a28e3': ['Computers and Electronics Retail'],
 '4e8501c16c25364d21d84052': ['Cafe, Coffee, and Tea House'],
 '4b0587b8f964a52012a122e3': ['Department Store'],
 '4d31962a72a8b1f7976495d0': ['Arcade'],
 '4c466ea60f5aa59310fe7a76': ['Restaurant'],
 '4b5e61e1f964a5204c8c29e3': ['Restaurant'],
 '4bdf9ada89ca76b046c15d5e': ['Cafeteria'],
 '4b5a8df8f964a52023cb28e3': ['Shopping Mall'],
 '4dbbae98b592b4962bd3d2bb': ['Education'],
 '4f6aacc3e4b0bcd825f07ba0': ['Restaurant'],
 '4b543a97f964a5200fb527e3': ['Education'],
 '4b5f89baf964a52046c029e3': ['Cafe, Coffee, and Tea House'],
 '4b66b596f964a5203a282be3': ['Food and Beverage Retail'],
 '4ce35c7431292c0f3c5cbeb6': ['Restaurant'],
 '4bccead4b6c49c744cab9491': ['Government Building'],
 '4b23b8f9f964a520915824e3': ['Health and Beauty Service'],
 '4e670af462e1706d82702919': ['Education'],
 '4d706e32b246a09319e71e5f': ['Restaurant'],
 '4b55c270f964a520b2ee27e3': ['Hobby Store'],
 '4bfb81a78f32ef3b261c05aa': ['Education'],
 '4ba0a9a4f964a520747637e3': ['Education'],
 '4deee804922e062b73c2cb78': ['Education'],
 '4e1c2d9018a8c65001f91bcc': ['Factory'],
 '4b612ca0f964a520fa0b2ae3': ['Hobby Store'],
 '4ea6671d8b814c68ace1af60': ['Bridge'],
 '4c10c5bc6b7e2d7f38142835': ['Bar'],
 '4c2ea57da0ced13a77500f6e': ['Shopping Mall'],
 '4bbaa87f7421a5937919c440': ['Restaurant'],
 '4cab2650a643b713b636eaa6': ['Restaurant'],
 '4b7e0978f964a52031e02fe3': ['Education'],
 '4b63fd49f964a520379a2ae3': ['Restaurant'],
 '4b1a59fcf964a52032e923e3': ['Bakery'],
 '4f100901e4b047204335354e': ['Food and Beverage Retail'],
 '4ed46cfbe3007ce6d723abbf': ['Health and Beauty Service'],
 '4b6f8061f964a52038f32ce3': ['Education'],
 '4be243bdb02ec9b686b64cc0': ['Restaurant'],
 '4b67a7fdf964a520be592be3': ['Bar'],
 '4ca68e9aa6e08cfa29167c94': ['Bridge'],
 '4b5292aaf964a520b48227e3': ['Sporting Goods Retail'],
 '4b751241f964a520fcfc2de3': ['Education'],
 '4cf0f8d26195721e27ad3ec1': ['Restaurant'],
 '4b99ca56f964a520ed9135e3': ['Structure'],
 '4bebe39a18389521e1ff0acf': ['Cafe, Coffee, and Tea House'],
 '4b9c6de9f964a520056836e3': ['Restaurant'],
 '4e2404f7c65b2b5e35602512': ['Bridge'],
 '4d379456b8d5a090688dfe1f': ['Restaurant'],
 '4ec1b060f5b93923c255dec8': ['Restaurant'],
 '4bc913fb511f95216023adc7': ['Convenience Store'],
 '4b5a75fcf964a5208cc628e3': ['Restaurant'],
 '4b63b174f964a5207a8c2ae3': ['Restaurant'],
 '4b5ace23f964a5206fd528e3': ['Music Store'],
 '4b5ea776f964a520119529e3': ['Computers and Electronics Retail'],
 '4e313fb8922ea20b3461ab49': ['Smoke Shop'],
 '4d4e18aea8fba1436fea3f1a': ['Restaurant'],
 '4bab392bf964a520359a3ae3': ['Pharmacy'],
 '4b7fa4f4f964a520023830e3': ['Performing Arts Venue'],
 '4bc294a7461576b0ecab7d32': ['Restaurant'],
 '4e3cf32ea809ba757c03a5a6': ['Music Store'],
 '4b63adf6f964a520a18b2ae3': ['Computers and Electronics Retail'],
 '4e4e0083b61cf637a4e182cc': ['Restaurant'],
 '4ba9d96bf964a5208c3a3ae3': ['Restaurant'],
 '4b5fce30f964a52063cd29e3': ['Financial Service'],
 '4b63ae30f964a520ac8b2ae3': ['Recycling Facility'],
 '4b7796aef964a520eea22ee3': ['Cafe, Coffee, and Tea House'],
 '4b9f4f7bf964a520fc1b37e3': ['Cafe, Coffee, and Tea House'],
 '4eeca95d02d514a36912b60f': ['Restaurant'],
 '4b5bfbfcf964a5201a2029e3': ['Miscellaneous Store'],
 '4d86e53e509137043f61b55b': ['Bowling Alley'],
 '4b27104df964a520898424e3': ['Restaurant'],
 '4e0847da483b98d417156e71': ['Library'],
 '4b0587a9f964a520d09e22e3': ['Shopping Mall'],
 '4d01bbee3be26dcb9e7374e4': ['Cafe, Coffee, and Tea House'],
 '4e61a620e4cdf1e2bef7cb8c': ['Education'],
 '4b591237f964a520227b28e3': ['Cafe, Coffee, and Tea House'],
 '4b5a3a54f964a520cdb528e3': ['Park'],
 '4d01c17b9f9ea143d2718ba9': ['Donut Shop'],
 '4b6bb59cf964a52051162ce3': ['Furniture and Home Store'],
 '4bce9721cc8cd13adfa9c4cf': ['Structure'],
 '4f587b3fe4b0055171786ed1': ['Computers and Electronics Retail'],
 '4ddd9349d22d28453ead46fd': ['Structure'],
 '4da11c39b521224bee12eeed': ['Gym and Studio'],
 '4be5398fd4f7c9b60b2c2520': ['Dessert Shop'],
 '4f58c086e4b01f47e88b0b22': ['States and Municipalities'],
 '4b91f97af964a520d0e133e3': ['Computers and Electronics Retail'],
 '4b767a5af964a520084e2ee3': ['Bar'],
 '4e3b87bcfa764553759e9a67': ['Cafe, Coffee, and Tea House'],
 '4be2aabaf07b0f4749dbf543': ['Health and Beauty Service'],
 '4b5ff761f964a520f1d129e3': ['Garden'],
 '4ef7e6038b81ef98d1141f1f': ['Restaurant'],

In [18]:
#retrieve venueIDs with more than one category
venueID2second_category = {k: v for k, v in venueID2second_category.items() if len(v) > 1}
len(venueID2second_category)

104

In [19]:
to_drop = venueID2second_category.keys()

df_cp_removed = df_cp[~df_cp["venueID"].isin(to_drop)]

In [20]:
to_drop_values = [item for sublist in venueID2second_category.values() for item in sublist]
to_drop_values = sorted(list(set(to_drop_values)))
to_drop_values

['Amusement Park',
 'Arcade',
 'Art Gallery',
 'Arts and Crafts Store',
 'Auditorium',
 'Automotive Retail',
 'Automotive Shop',
 'Bakery',
 'Bar',
 'Bookstore',
 'Cafe, Coffee, and Tea House',
 'Child Care Service',
 'Computers and Electronics Retail',
 'Convenience Store',
 'Convention Center',
 'Department Store',
 'Dessert Shop',
 'Education',
 'Event Space',
 'Eyecare Store',
 'Fashion Retail',
 'Food and Beverage Retail',
 'Furniture and Home Store',
 'Garden Center',
 'General Entertainment',
 'Gift Store',
 'Government Building',
 'Gym and Studio',
 'Health and Beauty Service',
 'Hiking Trail',
 'Hobby Store',
 'Hot Spring',
 'Library',
 'Lodging',
 'Market',
 'Miscellaneous Store',
 'Monument',
 'Movie Theater',
 'Museum',
 'Newsstand',
 'Night Club',
 'Other Great Outdoors',
 'Other Nightlife',
 'Performing Arts Venue',
 'Plaza',
 'Polling Place',
 'Public Art',
 'Recycling Facility',
 'Rest Area',
 'Restaurant',
 'Retail',
 'Running and Track',
 'Sculpture Garden',
 'Shopping Mall',
 'Snack Place',
 'Soccer',
 'Sporting Goods Retail',
 'Stadium',
 'States and Municipalities',
 'Strip Club',
 'Structure',
 'Tourist Information and Service',
 'Video Store',
 'Vintage and Thrift Store']

In [21]:
(len(df_cp) - len(df_cp_removed)) / len(df_cp)

0.011178982120593706

In [22]:
#drop third category
df_cp_removed.drop(columns=["Third_Category"], inplace=True)

/tmp/ipykernel_1448755/2630295318.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cp_removed.drop(columns=["Third_Category"], inplace=True)

In [23]:
df_cp = df_cp_removed

In [24]:
len(df_cp)

141968

In [25]:
df_cp

,uid,lat,lng,venueID,venue_descr,time,city_name,First_Category,Second_Category
0,114,35.714542,139.480065,4c16fdda96040f477cc473a5,Convenience Store,2012-04-03 19:12:07+00:00,Tokyo,Retail,Convenience Store
4,471,35.709190,139.773822,4ba88a28f964a52028df39e3,Ramen / Noodle House,2012-04-03 20:09:35+00:00,Tokyo,Dining and Drinking,Restaurant
5,589,35.609929,139.825659,4d69a46cde28224b27ff45be,Bridge,2012-04-03 20:09:41+00:00,Tokyo,Landmarks and Outdoors,Bridge
7,589,35.669933,139.825227,4d1bcae9f8ca236a2ff7f030,Other Great Outdoors,2012-04-03 20:38:19+00:00,Tokyo,Landmarks and Outdoors,Field
8,589,35.685405,139.826665,4d4f756eedc68eec0391b1a4,Bridge,2012-04-03 20:41:27+00:00,Tokyo,Landmarks and Outdoors,Bridge
...,...,...,...,...,...,...,...,...,...
273494,2020,35.639982,139.862180,4b9a6494f964a52072b135e3,Aquarium,2013-02-16 02:28:47+00:00,Tokyo,Arts and Entertainment,Aquarium
273495,491,35.562920,139.570410,4bb44966bd4b9c74738732f5,Post Office,2013-02-16 02:29:34+00:00,Tokyo,Community and Government,Government Building
273499,2277,35.710080,139.790999,4b82669cf964a5209ed130e3,Post Office,2013-02-16 02:33:48+00:00,Tokyo,Community and Government,Government Building
273501,326,35.656939,139.702518,4bab3456f964a5204d993ae3,Music Venue,2013-02-16 02:34:35+00:00,Tokyo,Arts and Entertainment,Performing Arts Venue
273502,1050,35.704069,139.579496,4b5a7486f964a52027c628e3,Record Shop,2013-02-16 02:35:29+00:00,Tokyo,Retail,Record Store

In [26]:
import os
if not os.path.exists("data/processed/foursquare_complete_tky_cp_full_sampled.csv"):
    df_cp.to_csv("data/processed/foursquare_complete_tky_cp_full_sampled.csv")